--
-- GET_PEN_STATUS_DT_TEST  (Function) 
--
CREATE OR REPLACE FUNCTION OLIVER.GET_PEN_STATUS_DT_TEST(CLT_ID VARCHAR2,PL_ID VARCHAR2,MEM_ID VARCHAR2,DT DATE) RETURN VARCHAR2 AS
ST VARCHAR2(10);
BEGIN
SELECT MAX(A.TMPSH_STATUS) INTO ST FROM TBL_MEM_PEN_STATUS_HIST A WHERE A.TMPSH_CLIENT=CLT_ID AND A.TMPSH_PLAN=PL_ID AND A.TMPSH_MEM_ID=MEM_ID AND A.tmpsh_status_date>=DT AND A.TMPSH_STATUS NOT IN ('C','A') AND A.TMPSH_STATUS_DATE<= (SELECT NVL(MIN(B.TMPSH_STATUS_DATE),A.TMPSH_STATUS_DATE) FROM TBL_MEM_PEN_STATUS_HIST B WHERE A.TMPSH_CLIENT=B.TMPSH_CLIENT AND A.TMPSH_PLAN=B.TMPSH_PLAN AND A.TMPSH_MEM_ID=B.TMPSH_MEM_ID AND B.TMPSH_STATUS IN ('C','A') AND B.TMPSH_STATUS_DATE>DT);
IF ST IS NULL THEN
    SELECT MAX(A.TMPSH_STATUS) INTO ST FROM TBL_MEM_PEN_STATUS_HIST A WHERE A.TMPSH_CLIENT=CLT_ID AND A.TMPSH_PLAN=PL_ID AND A.TMPSH_MEM_ID=MEM_ID AND A.tmpsh_status_date=(SELECT MAX(B.TMPSH_STATUS_DATE)  FROM TBL_MEM_PEN_STATUS_HIST B WHERE B.TMPSH_CLIENT=CLT_ID AND B.TMPSH_PLAN=PL_ID AND B.TMPSH_MEM_ID=MEM_ID AND B.TMPSH_STATUS_DATE<=DT);
     
    IF ST IS NULL THEN
    
    
       SELECT MAX(A.TMPSH_STATUS) INTO ST FROM TBL_MEM_PEN_STATUS_HIST A WHERE A.TMPSH_CLIENT=CLT_ID AND A.TMPSH_PLAN=PL_ID AND A.TMPSH_MEM_ID=MEM_ID AND A.tmpsh_status_date=(SELECT MIN(B.TMPSH_STATUS_DATE)  FROM TBL_MEM_PEN_STATUS_HIST B WHERE B.TMPSH_CLIENT=CLT_ID AND B.TMPSH_PLAN=PL_ID AND B.TMPSH_MEM_ID=MEM_ID AND B.TMPSH_STATUS_DATE>=DT);
    END IF;
END IF;
RETURN ST;
END;
/

