--
-- DBA  (Role) 
--
CREATE ROLE DBA NOT IDENTIFIED;

-- Object privileges granted to DBA
GRANT EXECUTE ON SYS.ADR_HOME_T TO DBA;
GRANT EXECUTE ON SYS.ADR_INCIDENT_CORR_KEYS_T TO DBA;
GRANT EXECUTE ON SYS.ADR_INCIDENT_FILES_T TO DBA;
GRANT EXECUTE ON SYS.ADR_INCIDENT_INFO_T TO DBA;
GRANT EXECUTE ON SYS.ADR_INCIDENT_T TO DBA;
GRANT EXECUTE ON SYS.ADR_LOG_MSG_ARGS_T TO DBA;
GRANT EXECUTE ON SYS.ADR_LOG_MSG_ARG_T TO DBA;
GRANT EXECUTE ON SYS.ADR_LOG_MSG_ECID_T TO DBA;
GRANT EXECUTE ON SYS.ADR_LOG_MSG_ERRID_T TO DBA;
GRANT EXECUTE ON SYS.ADR_LOG_MSG_SUPPL_ATTRS_T TO DBA;
GRANT EXECUTE ON SYS.ADR_LOG_MSG_SUPPL_ATTR_T TO DBA;
GRANT EXECUTE ON SYS.ADR_LOG_MSG_T TO DBA;
GRANT EXECUTE ON SYS.AS_REPLAY TO DBA;
GRANT EXECUTE ON ORDSYS.CARTRIDGE TO DBA;
GRANT SELECT ON SYS.CDB_XS_ACTIVE_SESSIONS TO DBA;
GRANT SELECT ON SYS.CDB_XS_SESSIONS TO DBA;
GRANT SELECT ON SYS.CDB_XS_SESSION_NS_ATTRIBUTES TO DBA;
GRANT SELECT ON SYS.CDB_XS_SESSION_ROLES TO DBA;
GRANT SELECT ON SYS.DBA_XS_ACTIVE_SESSIONS TO DBA;
GRANT SELECT ON SYS.DBA_XS_SESSIONS TO DBA;
GRANT SELECT ON SYS.DBA_XS_SESSION_NS_ATTRIBUTES TO DBA;
GRANT SELECT ON SYS.DBA_XS_SESSION_ROLES TO DBA;
GRANT EXECUTE ON SYS.DBMS_ADR TO DBA;
GRANT EXECUTE ON SYS.DBMS_ADR_APP TO DBA;
GRANT EXECUTE ON SYS.DBMS_APP_CONT TO DBA;
GRANT EXECUTE ON SYS.DBMS_AUTO_SQLTUNE TO DBA;
GRANT EXECUTE ON SYS.DBMS_AUTO_TASK_ADMIN TO DBA;
GRANT EXECUTE ON SYS.DBMS_AUTO_TASK_IMMEDIATE TO DBA;
GRANT EXECUTE ON SYS.DBMS_CACHEUTIL TO DBA;
GRANT EXECUTE ON XDB.DBMS_CSX_ADMIN TO DBA;
GRANT EXECUTE ON SYS.DBMS_DNFS TO DBA;
GRANT EXECUTE ON SYS.DBMS_FEATURE_USAGE_REPORT TO DBA;
GRANT EXECUTE ON SYS.DBMS_FLASHBACK TO DBA;
GRANT EXECUTE ON SYS.DBMS_FLASHBACK_ARCHIVE TO DBA;
GRANT EXECUTE ON SYS.DBMS_FS TO DBA;
GRANT EXECUTE ON SYS.DBMS_GSM_FIX TO DBA;
GRANT EXECUTE ON SYS.DBMS_HANG_MANAGER TO DBA;
GRANT EXECUTE ON SYS.DBMS_HM TO DBA;
GRANT EXECUTE ON SYS.DBMS_ILM_ADMIN TO DBA;
GRANT EXECUTE ON SYS.DBMS_INMEMORY_ADMIN TO DBA;
GRANT EXECUTE ON SYS.DBMS_IR TO DBA;
GRANT EXECUTE ON SYS.DBMS_LOGSTDBY TO DBA;
GRANT EXECUTE ON SYS.DBMS_MANAGEMENT_BOOTSTRAP TO DBA;
GRANT EXECUTE ON SYS.DBMS_MONITOR TO DBA;
GRANT EXECUTE ON SYS.DBMS_NETWORK_ACL_ADMIN TO DBA;
GRANT EXECUTE ON SYS.DBMS_PERF TO DBA;
GRANT EXECUTE ON SYS.DBMS_RAT_MASK TO DBA;
GRANT EXECUTE ON SYS.DBMS_RESULT_CACHE TO DBA;
GRANT EXECUTE ON SYS.DBMS_RESUMABLE TO DBA;
GRANT EXECUTE ON SYS.DBMS_ROLLING TO DBA;
GRANT EXECUTE ON SYS.DBMS_SERVER_ALERT TO DBA;
GRANT EXECUTE ON SYS.DBMS_SERVER_TRACE TO DBA;
GRANT EXECUTE ON SYS.DBMS_SERVICE TO DBA;
GRANT EXECUTE ON SYS.DBMS_SERVICE_CONST TO DBA;
GRANT EXECUTE ON SYS.DBMS_SERVICE_ERR TO DBA;
GRANT EXECUTE ON SYS.DBMS_SERVICE_PRVT TO DBA;
GRANT EXECUTE ON SYS.DBMS_STORAGE_MAP TO DBA;
GRANT EXECUTE ON SYS.DBMS_TDB TO DBA;
GRANT EXECUTE ON SYS.DBMS_TNS TO DBA;
GRANT EXECUTE ON SYS.DBMS_UADV_ARR TO DBA;
GRANT EXECUTE ON SYS.DBMS_UMF TO DBA;
GRANT EXECUTE ON SYS.DBMS_UNDO_ADV TO DBA;
GRANT EXECUTE ON SYS.DBMS_WORKLOAD_CAPTURE TO DBA;
GRANT EXECUTE ON SYS.DBMS_WORKLOAD_REPLAY TO DBA;
GRANT EXECUTE ON SYS.DBMS_WORKLOAD_REPOSITORY TO DBA;
GRANT EXECUTE ON SYS.DBMS_WRR_STATE TO DBA;
GRANT EXECUTE ON XDB.DBMS_XDBT TO DBA;
GRANT EXECUTE ON XDB.DBMS_XDB_ADMIN TO DBA;
GRANT EXECUTE ON SYS.DBMS_XS_PRINCIPALS TO DBA;
GRANT EXECUTE ON SYS.HM_SQLTK_INTERNAL TO DBA;
GRANT EXECUTE ON SYS.LOAD_UNDO_STAT TO DBA;
GRANT DELETE ON SYS.MAP_OBJECT TO DBA;
GRANT UPDATE ON SYS.MAP_OBJECT TO DBA;
GRANT SELECT ON SYS.MAP_OBJECT TO DBA;
GRANT INSERT ON SYS.MAP_OBJECT TO DBA;
GRANT EXECUTE ON SYS.OJDS_CONTEXT TO DBA;
GRANT EXECUTE ON SYS.ORD_ADMIN TO DBA;
GRANT EXECUTE ON SYS.OUTLN_EDIT_PKG TO DBA;
GRANT EXECUTE ON SYS.OUTLN_PKG TO DBA;
GRANT EXECUTE ON SYS.RESET_UNDO_STAT TO DBA;
GRANT SELECT ON SYS.V_$DIAG_ADR_CONTROL TO DBA;
GRANT SELECT ON SYS.V_$DIAG_ADR_CONTROL_AUX TO DBA;
GRANT SELECT ON SYS.V_$DIAG_ADR_INVALIDATION TO DBA;
GRANT SELECT ON SYS.V_$DIAG_ALERT_EXT TO DBA;
GRANT SELECT ON SYS.V_$DIAG_AMS_XACTION TO DBA;
GRANT SELECT ON SYS.V_$DIAG_DDE_USER_ACTION TO DBA;
GRANT SELECT ON SYS.V_$DIAG_DDE_USER_ACTION_DEF TO DBA;
GRANT SELECT ON SYS.V_$DIAG_DDE_USR_ACT_PARAM TO DBA;
GRANT SELECT ON SYS.V_$DIAG_DDE_USR_ACT_PARAM_DEF TO DBA;
GRANT SELECT ON SYS.V_$DIAG_DDE_USR_INC_ACT_MAP TO DBA;
GRANT SELECT ON SYS.V_$DIAG_DDE_USR_INC_TYPE TO DBA;
GRANT SELECT ON SYS.V_$DIAG_DFW_CONFIG_CAPTURE TO DBA;
GRANT SELECT ON SYS.V_$DIAG_DFW_CONFIG_ITEM TO DBA;
GRANT SELECT ON SYS.V_$DIAG_DFW_PATCH_CAPTURE TO DBA;
GRANT SELECT ON SYS.V_$DIAG_DFW_PATCH_ITEM TO DBA;
GRANT SELECT ON SYS.V_$DIAG_DFW_PURGE TO DBA;
GRANT SELECT ON SYS.V_$DIAG_DFW_PURGE_ITEM TO DBA;
GRANT SELECT ON SYS.V_$DIAG_DIAGV_INCIDENT TO DBA;
GRANT SELECT ON SYS.V_$DIAG_DIR_EXT TO DBA;
GRANT SELECT ON SYS.V_$DIAG_EM_DIAG_JOB TO DBA;
GRANT SELECT ON SYS.V_$DIAG_EM_TARGET_INFO TO DBA;
GRANT SELECT ON SYS.V_$DIAG_EM_USER_ACTIVITY TO DBA;
GRANT SELECT ON SYS.V_$DIAG_HM_FDG_SET TO DBA;
GRANT SELECT ON SYS.V_$DIAG_HM_FINDING TO DBA;
GRANT SELECT ON SYS.V_$DIAG_HM_INFO TO DBA;
GRANT SELECT ON SYS.V_$DIAG_HM_MESSAGE TO DBA;
GRANT SELECT ON SYS.V_$DIAG_HM_RECOMMENDATION TO DBA;
GRANT SELECT ON SYS.V_$DIAG_HM_RUN TO DBA;
GRANT SELECT ON SYS.V_$DIAG_INCCKEY TO DBA;
GRANT SELECT ON SYS.V_$DIAG_INCIDENT TO DBA;
GRANT SELECT ON SYS.V_$DIAG_INCIDENT_FILE TO DBA;
GRANT SELECT ON SYS.V_$DIAG_INC_METER_CONFIG TO DBA;
GRANT SELECT ON SYS.V_$DIAG_INC_METER_IMPT_DEF TO DBA;
GRANT SELECT ON SYS.V_$DIAG_INC_METER_INFO TO DBA;
GRANT SELECT ON SYS.V_$DIAG_INC_METER_PK_IMPTS TO DBA;
GRANT SELECT ON SYS.V_$DIAG_INC_METER_SUMMARY TO DBA;
GRANT SELECT ON SYS.V_$DIAG_IPS_CONFIGURATION TO DBA;
GRANT SELECT ON SYS.V_$DIAG_IPS_FILE_COPY_LOG TO DBA;
GRANT SELECT ON SYS.V_$DIAG_IPS_FILE_METADATA TO DBA;
GRANT SELECT ON SYS.V_$DIAG_IPS_PACKAGE TO DBA;
GRANT SELECT ON SYS.V_$DIAG_IPS_PACKAGE_FILE TO DBA;
GRANT SELECT ON SYS.V_$DIAG_IPS_PACKAGE_HISTORY TO DBA;
GRANT SELECT ON SYS.V_$DIAG_IPS_PACKAGE_INCIDENT TO DBA;
GRANT SELECT ON SYS.V_$DIAG_IPS_PKG_UNPACK_HIST TO DBA;
GRANT SELECT ON SYS.V_$DIAG_IPS_PROGRESS_LOG TO DBA;
GRANT SELECT ON SYS.V_$DIAG_IPS_REMOTE_PACKAGE TO DBA;
GRANT SELECT ON SYS.V_$DIAG_LOG_EXT TO DBA;
GRANT SELECT ON SYS.V_$DIAG_PDB_PROBLEM TO DBA;
GRANT SELECT ON SYS.V_$DIAG_PDB_SPACE_MGMT TO DBA;
GRANT SELECT ON SYS.V_$DIAG_PICKLEERR TO DBA;
GRANT SELECT ON SYS.V_$DIAG_PROBLEM TO DBA;
GRANT SELECT ON SYS.V_$DIAG_RELMD_EXT TO DBA;
GRANT SELECT ON SYS.V_$DIAG_SWEEPERR TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VEM_USER_ACTLOG TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VEM_USER_ACTLOG1 TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VHM_RUN TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VIEW TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VIEWCOL TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VINCIDENT TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VINCIDENT_FILE TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VINC_METER_INFO TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VIPS_FILE_COPY_LOG TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VIPS_FILE_METADATA TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VIPS_PACKAGE_FILE TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VIPS_PACKAGE_HISTORY TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VIPS_PACKAGE_MAIN_INT TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VIPS_PACKAGE_SIZE TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VIPS_PKG_FILE TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VIPS_PKG_INC_CAND TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VIPS_PKG_INC_DTL TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VIPS_PKG_INC_DTL1 TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VIPS_PKG_MAIN_PROBLEM TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VNOT_EXIST_INCIDENT TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VPDB_PROBLEM TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VPROBLEM TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VPROBLEM1 TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VPROBLEM2 TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VPROBLEM_BUCKET TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VPROBLEM_BUCKET1 TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VPROBLEM_BUCKET_COUNT TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VPROBLEM_INT TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VPROBLEM_LASTINC TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VSHOWCATVIEW TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VSHOWINCB TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VSHOWINCB_I TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VTEST_EXISTS TO DBA;
GRANT SELECT ON SYS.V_$DIAG_V_ACTINC TO DBA;
GRANT SELECT ON SYS.V_$DIAG_V_ACTPROB TO DBA;
GRANT SELECT ON SYS.V_$DIAG_V_INCCOUNT TO DBA;
GRANT SELECT ON SYS.V_$DIAG_V_INCFCOUNT TO DBA;
GRANT SELECT ON SYS.V_$DIAG_V_INC_METER_INFO_PROB TO DBA;
GRANT SELECT ON SYS.V_$DIAG_V_IPSPRBCNT TO DBA;
GRANT SELECT ON SYS.V_$DIAG_V_IPSPRBCNT1 TO DBA;
GRANT SELECT ON SYS.V_$DIAG_V_NFCINC TO DBA;
GRANT SELECT ON SYS.V_$DIAG_V_SWPERRCOUNT TO DBA;
GRANT DELETE ON XDB.X$PT6A0WVGOTVN9KD9IOC5OF8P6HD7 TO DBA;
GRANT INSERT ON XDB.X$PT6A0WVGOTVN9KD9IOC5OF8P6HD7 TO DBA;
GRANT SELECT ON XDB.X$PT6A0WVGOTVN9KD9IOC5OF8P6HD7 TO DBA;
GRANT UPDATE ON XDB.X$PT6A0WVGOTVN9KD9IOC5OF8P6HD7 TO DBA;
GRANT SELECT ON XDB.XDB$ACL TO DBA;
GRANT UPDATE ON XDB.XDB$ACL TO DBA;
GRANT INSERT ON XDB.XDB$ACL TO DBA;
GRANT DELETE ON XDB.XDB$ACL TO DBA;
GRANT DELETE ON XDB.XDB$CHECKOUTS TO DBA;
GRANT UPDATE ON XDB.XDB$CHECKOUTS TO DBA;
GRANT INSERT ON XDB.XDB$CHECKOUTS TO DBA;
GRANT SELECT ON XDB.XDB$CHECKOUTS TO DBA;
GRANT INSERT ON XDB.XDB$CONFIG TO DBA;
GRANT UPDATE ON XDB.XDB$CONFIG TO DBA;
GRANT SELECT ON XDB.XDB$CONFIG TO DBA;
GRANT DELETE ON XDB.XDB$CONFIG TO DBA;
GRANT SELECT ON XDB.XDB$D_LINK TO DBA;
GRANT UPDATE ON XDB.XDB$D_LINK TO DBA;
GRANT DELETE ON XDB.XDB$D_LINK TO DBA;
GRANT INSERT ON XDB.XDB$D_LINK TO DBA;
GRANT SELECT ON XDB.XDB$H_INDEX TO DBA;
GRANT UPDATE ON XDB.XDB$H_INDEX TO DBA;
GRANT INSERT ON XDB.XDB$H_INDEX TO DBA;
GRANT DELETE ON XDB.XDB$H_INDEX TO DBA;
GRANT DELETE ON XDB.XDB$H_LINK TO DBA;
GRANT INSERT ON XDB.XDB$H_LINK TO DBA;
GRANT SELECT ON XDB.XDB$H_LINK TO DBA;
GRANT UPDATE ON XDB.XDB$H_LINK TO DBA;
GRANT UPDATE ON XDB.XDB$NLOCKS TO DBA;
GRANT DELETE ON XDB.XDB$NLOCKS TO DBA;
GRANT INSERT ON XDB.XDB$NLOCKS TO DBA;
GRANT SELECT ON XDB.XDB$NLOCKS TO DBA;
GRANT INSERT ON XDB.XDB$RESCONFIG TO DBA;
GRANT DELETE ON XDB.XDB$RESCONFIG TO DBA;
GRANT UPDATE ON XDB.XDB$RESCONFIG TO DBA;
GRANT SELECT ON XDB.XDB$RESCONFIG TO DBA;
GRANT SELECT ON XDB.XDB$RESOURCE TO DBA;
GRANT INSERT ON XDB.XDB$RESOURCE TO DBA;
GRANT DELETE ON XDB.XDB$RESOURCE TO DBA;
GRANT UPDATE ON XDB.XDB$RESOURCE TO DBA;
GRANT SELECT ON SYS.XSDB$SCHEMA_ACL TO DBA;
GRANT INSERT ON SYS.XSDB$SCHEMA_ACL TO DBA;
GRANT UPDATE ON SYS.XSDB$SCHEMA_ACL TO DBA;
GRANT EXECUTE ON SYS.XS_MTCACHE_INT TO DBA;

-- System privileges granted to DBA
GRANT CREATE SESSION TO DBA;
GRANT ALTER SESSION TO DBA;
GRANT DROP TABLESPACE TO DBA;
GRANT BECOME USER TO DBA;
GRANT DROP ROLLBACK SEGMENT TO DBA;
GRANT SELECT ANY TABLE TO DBA;
GRANT INSERT ANY TABLE TO DBA;
GRANT UPDATE ANY TABLE TO DBA;
GRANT DROP ANY INDEX TO DBA;
GRANT SELECT ANY SEQUENCE TO DBA;
GRANT CREATE ROLE TO DBA;
GRANT EXECUTE ANY PROCEDURE TO DBA;
GRANT ALTER PROFILE TO DBA;
GRANT CREATE ANY DIRECTORY TO DBA;
GRANT CREATE ANY LIBRARY TO DBA;
GRANT EXECUTE ANY LIBRARY TO DBA;
GRANT ALTER ANY INDEXTYPE TO DBA;
GRANT DROP ANY INDEXTYPE TO DBA;
BEGIN
SYS.DBMS_AQADM.GRANT_SYSTEM_PRIVILEGE (
  PRIVILEGE    => 'DEQUEUE_ANY',
  GRANTEE      => 'DBA',
  ADMIN_OPTION => FALSE);
END;
/
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.EXECUTE_ANY_EVALUATION_CONTEXT,
  GRANTEE      => 'DBA',
  GRANT_OPTION => FALSE);
END;
/
GRANT EXPORT FULL DATABASE TO DBA;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_RULE_OBJ,
  GRANTEE      => 'DBA',
  GRANT_OPTION => FALSE);
END;
/
GRANT ALTER ANY SQL PROFILE TO DBA;
GRANT ADMINISTER ANY SQL TUNING SET TO DBA;
GRANT CHANGE NOTIFICATION TO DBA;
GRANT DROP ANY EDITION TO DBA;
GRANT DROP ANY MINING MODEL TO DBA;
GRANT ALTER ANY MINING MODEL TO DBA;
GRANT ALTER ANY CUBE DIMENSION TO DBA;
GRANT CREATE CUBE TO DBA;
GRANT DROP ANY CUBE BUILD PROCESS TO DBA;
GRANT USE ANY SQL TRANSLATION PROFILE TO DBA;
GRANT CREATE PLUGGABLE DATABASE TO DBA;
GRANT ALTER ROLLBACK SEGMENT TO DBA;
GRANT DELETE ANY TABLE TO DBA;
GRANT ALTER DATABASE TO DBA;
GRANT FORCE ANY TRANSACTION TO DBA;
GRANT ALTER ANY PROCEDURE TO DBA;
GRANT DROP ANY TRIGGER TO DBA;
GRANT DROP ANY MATERIALIZED VIEW TO DBA;
GRANT UNDER ANY TYPE TO DBA;
GRANT ALTER ANY LIBRARY TO DBA;
GRANT CREATE DIMENSION TO DBA;
GRANT DEBUG ANY PROCEDURE TO DBA;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_RULE_SET_OBJ,
  GRANTEE      => 'DBA',
  GRANT_OPTION => FALSE);
END;
/
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.ALTER_ANY_RULE_SET,
  GRANTEE      => 'DBA',
  GRANT_OPTION => FALSE);
END;
/
GRANT ANALYZE ANY DICTIONARY TO DBA;
GRANT ALTER ANY EDITION TO DBA;
GRANT CREATE ANY ASSEMBLY TO DBA;
GRANT ALTER ANY CUBE TO DBA;
GRANT SELECT ANY CUBE TO DBA;
GRANT DROP ANY MEASURE FOLDER TO DBA;
GRANT USE ANY JOB RESOURCE TO DBA;
GRANT ALTER ANY ATTRIBUTE DIMENSION TO DBA;
GRANT DROP ANY HIERARCHY TO DBA;
GRANT RESTRICTED SESSION TO DBA;
GRANT CREATE TABLESPACE TO DBA;
GRANT ALTER TABLESPACE TO DBA;
GRANT CREATE USER TO DBA;
GRANT ALTER USER TO DBA;
GRANT LOCK ANY TABLE TO DBA;
GRANT CREATE VIEW TO DBA;
GRANT DROP ANY VIEW TO DBA;
GRANT GRANT ANY ROLE TO DBA;
GRANT CREATE TRIGGER TO DBA;
GRANT CREATE TYPE TO DBA;
GRANT EXECUTE ANY OPERATOR TO DBA;
GRANT CREATE ANY DIMENSION TO DBA;
GRANT ALTER ANY DIMENSION TO DBA;
GRANT CREATE ANY OUTLINE TO DBA;
GRANT ADMINISTER DATABASE TRIGGER TO DBA;
GRANT RESUMABLE TO DBA;
GRANT FLASHBACK ANY TABLE TO DBA;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_ANY_RULE_SET,
  GRANTEE      => 'DBA',
  GRANT_OPTION => FALSE);
END;
/
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.EXECUTE_ANY_RULE_SET,
  GRANTEE      => 'DBA',
  GRANT_OPTION => FALSE);
END;
/
GRANT IMPORT FULL DATABASE TO DBA;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.EXECUTE_ANY_RULE,
  GRANTEE      => 'DBA',
  GRANT_OPTION => FALSE);
END;
/
GRANT EXECUTE ANY PROGRAM TO DBA;
GRANT CREATE ANY EDITION TO DBA;
GRANT CREATE ASSEMBLY TO DBA;
GRANT ALTER ANY ASSEMBLY TO DBA;
GRANT CREATE CUBE DIMENSION TO DBA;
GRANT CREATE ANY CUBE BUILD PROCESS TO DBA;
GRANT UPDATE ANY CUBE DIMENSION TO DBA;
GRANT EM EXPRESS CONNECT TO DBA;
GRANT SET CONTAINER TO DBA;
GRANT ALTER ANY MEASURE FOLDER TO DBA;
GRANT DROP ANY ATTRIBUTE DIMENSION TO DBA;
GRANT CREATE HIERARCHY TO DBA;
GRANT CREATE ANALYTIC VIEW TO DBA;
GRANT CREATE ANY TABLE TO DBA;
GRANT CREATE ANY INDEX TO DBA;
GRANT CREATE ANY SEQUENCE TO DBA;
GRANT ALTER ANY ROLE TO DBA;
GRANT ANALYZE ANY TO DBA;
GRANT DROP ANY LIBRARY TO DBA;
GRANT CREATE ANY OPERATOR TO DBA;
GRANT CREATE INDEXTYPE TO DBA;
GRANT UNDER ANY TABLE TO DBA;
GRANT DROP ANY DIMENSION TO DBA;
GRANT SELECT ANY DICTIONARY TO DBA;
GRANT GRANT ANY OBJECT PRIVILEGE TO DBA;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_EVALUATION_CONTEXT_OBJ,
  GRANTEE      => 'DBA',
  GRANT_OPTION => FALSE);
END;
/
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_ANY_EVALUATION_CONTEXT,
  GRANTEE      => 'DBA',
  GRANT_OPTION => FALSE);
END;
/
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.DROP_ANY_EVALUATION_CONTEXT,
  GRANTEE      => 'DBA',
  GRANT_OPTION => FALSE);
END;
/
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_ANY_RULE,
  GRANTEE      => 'DBA',
  GRANT_OPTION => FALSE);
END;
/
GRANT CREATE JOB TO DBA;
GRANT CREATE ANY JOB TO DBA;
GRANT CREATE MINING MODEL TO DBA;
GRANT INSERT ANY CUBE DIMENSION TO DBA;
GRANT DROP ANY CUBE TO DBA;
GRANT UPDATE ANY CUBE BUILD PROCESS TO DBA;
GRANT EXEMPT DML REDACTION POLICY TO DBA;
GRANT READ ANY TABLE TO DBA;
GRANT ALTER SYSTEM TO DBA;
GRANT AUDIT SYSTEM TO DBA;
GRANT CREATE ROLLBACK SEGMENT TO DBA;
GRANT DROP ANY TABLE TO DBA;
GRANT COMMENT ANY TABLE TO DBA;
GRANT REDEFINE ANY TABLE TO DBA;
GRANT CREATE CLUSTER TO DBA;
GRANT ALTER ANY INDEX TO DBA;
GRANT DROP PUBLIC DATABASE LINK TO DBA;
GRANT CREATE PROFILE TO DBA;
GRANT ALTER ANY MATERIALIZED VIEW TO DBA;
GRANT ALTER ANY TYPE TO DBA;
GRANT DROP ANY TYPE TO DBA;
GRANT UNDER ANY VIEW TO DBA;
GRANT EXECUTE ANY INDEXTYPE TO DBA;
GRANT DROP ANY CONTEXT TO DBA;
GRANT ALTER ANY OUTLINE TO DBA;
BEGIN
SYS.DBMS_RESOURCE_MANAGER_PRIVS.GRANT_SYSTEM_PRIVILEGE
  (GRANTEE_NAME   => 'DBA', 
   PRIVILEGE_NAME => 'ADMINISTER_RESOURCE_MANAGER',
   ADMIN_OPTION   => FALSE);
END;
/
GRANT MANAGE SCHEDULER TO DBA;
GRANT MANAGE FILE GROUP TO DBA;
GRANT CREATE ANY MINING MODEL TO DBA;
GRANT SELECT ANY MINING MODEL TO DBA;
GRANT CREATE ANY MEASURE FOLDER TO DBA;
GRANT DELETE ANY MEASURE FOLDER TO DBA;
GRANT CREATE ANY SQL TRANSLATION PROFILE TO DBA;
GRANT CREATE ANY CREDENTIAL TO DBA;
GRANT EXEMPT DDL REDACTION POLICY TO DBA;
GRANT SELECT ANY MEASURE FOLDER TO DBA;
GRANT SELECT ANY CUBE BUILD PROCESS TO DBA;
GRANT ALTER ANY CUBE BUILD PROCESS TO DBA;
GRANT CREATE ANY HIERARCHY TO DBA;
GRANT CREATE TABLE TO DBA;
GRANT BACKUP ANY TABLE TO DBA;
GRANT CREATE ANY CLUSTER TO DBA;
GRANT DROP ANY SYNONYM TO DBA;
GRANT DROP PUBLIC SYNONYM TO DBA;
GRANT CREATE ANY VIEW TO DBA;
GRANT CREATE SEQUENCE TO DBA;
GRANT ALTER ANY SEQUENCE TO DBA;
GRANT FORCE TRANSACTION TO DBA;
GRANT CREATE PROCEDURE TO DBA;
GRANT CREATE ANY PROCEDURE TO DBA;
GRANT ALTER RESOURCE COST TO DBA;
GRANT DROP ANY DIRECTORY TO DBA;
GRANT CREATE ANY TYPE TO DBA;
GRANT ALTER ANY OPERATOR TO DBA;
GRANT CREATE ANY INDEXTYPE TO DBA;
BEGIN
SYS.DBMS_AQADM.GRANT_SYSTEM_PRIVILEGE (
  PRIVILEGE    => 'ENQUEUE_ANY',
  GRANTEE      => 'DBA',
  ADMIN_OPTION => FALSE);
END;
/
GRANT ON COMMIT REFRESH TO DBA;
GRANT DEBUG CONNECT SESSION TO DBA;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.DROP_ANY_RULE_SET,
  GRANTEE      => 'DBA',
  GRANT_OPTION => FALSE);
END;
/
GRANT EXECUTE ANY CLASS TO DBA;
GRANT MANAGE ANY FILE GROUP TO DBA;
GRANT EXECUTE ANY ASSEMBLY TO DBA;
GRANT EXECUTE ASSEMBLY TO DBA;
GRANT COMMENT ANY MINING MODEL TO DBA;
GRANT CREATE ANY CUBE DIMENSION TO DBA;
GRANT DELETE ANY CUBE DIMENSION TO DBA;
GRANT SELECT ANY CUBE DIMENSION TO DBA;
GRANT DROP ANY SQL TRANSLATION PROFILE TO DBA;
GRANT CREATE LOCKDOWN PROFILE TO DBA;
GRANT DROP LOCKDOWN PROFILE TO DBA;
GRANT CREATE CREDENTIAL TO DBA;
GRANT CREATE ANY ATTRIBUTE DIMENSION TO DBA;
GRANT ALTER ANY TABLE TO DBA;
GRANT DROP ANY CLUSTER TO DBA;
GRANT CREATE SYNONYM TO DBA;
GRANT CREATE PUBLIC SYNONYM TO DBA;
GRANT DROP ANY SEQUENCE TO DBA;
GRANT DROP ANY ROLE TO DBA;
GRANT AUDIT ANY TO DBA;
GRANT DROP ANY PROCEDURE TO DBA;
GRANT CREATE ANY TRIGGER TO DBA;
GRANT ALTER ANY TRIGGER TO DBA;
GRANT DROP PROFILE TO DBA;
GRANT GRANT ANY PRIVILEGE TO DBA;
GRANT CREATE LIBRARY TO DBA;
GRANT CREATE OPERATOR TO DBA;
GRANT DROP ANY OUTLINE TO DBA;
GRANT MERGE ANY VIEW TO DBA;
GRANT ADMINISTER SQL TUNING SET TO DBA;
GRANT UPDATE ANY CUBE TO DBA;
GRANT INSERT ANY MEASURE FOLDER TO DBA;
GRANT ADMINISTER SQL MANAGEMENT OBJECT TO DBA;
GRANT CREATE SQL TRANSLATION PROFILE TO DBA;
GRANT LOGMINING TO DBA;
GRANT ALTER ANY HIERARCHY TO DBA;
GRANT ALTER ANY ANALYTIC VIEW TO DBA;
GRANT DROP ANY ANALYTIC VIEW TO DBA;
GRANT MANAGE TABLESPACE TO DBA;
GRANT DROP USER TO DBA;
GRANT ALTER ANY CLUSTER TO DBA;
GRANT CREATE ANY SYNONYM TO DBA;
GRANT CREATE DATABASE LINK TO DBA;
GRANT CREATE PUBLIC DATABASE LINK TO DBA;
GRANT CREATE MATERIALIZED VIEW TO DBA;
GRANT CREATE ANY MATERIALIZED VIEW TO DBA;
GRANT EXECUTE ANY TYPE TO DBA;
GRANT DROP ANY OPERATOR TO DBA;
GRANT QUERY REWRITE TO DBA;
GRANT GLOBAL QUERY REWRITE TO DBA;
BEGIN
SYS.DBMS_AQADM.GRANT_SYSTEM_PRIVILEGE (
  PRIVILEGE    => 'MANAGE_ANY',
  GRANTEE      => 'DBA',
  ADMIN_OPTION => FALSE);
END;
/
GRANT CREATE ANY CONTEXT TO DBA;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.ALTER_ANY_EVALUATION_CONTEXT,
  GRANTEE      => 'DBA',
  GRANT_OPTION => FALSE);
END;
/
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.ALTER_ANY_RULE,
  GRANTEE      => 'DBA',
  GRANT_OPTION => FALSE);
END;
/
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.DROP_ANY_RULE,
  GRANTEE      => 'DBA',
  GRANT_OPTION => FALSE);
END;
/
GRANT ADVISOR TO DBA;
GRANT SELECT ANY TRANSACTION TO DBA;
GRANT DROP ANY SQL PROFILE TO DBA;
GRANT CREATE ANY SQL PROFILE TO DBA;
GRANT READ ANY FILE GROUP TO DBA;
GRANT CREATE EXTERNAL JOB TO DBA;
GRANT DROP ANY ASSEMBLY TO DBA;
GRANT DROP ANY CUBE DIMENSION TO DBA;
GRANT CREATE ANY CUBE TO DBA;
GRANT CREATE MEASURE FOLDER TO DBA;
GRANT CREATE CUBE BUILD PROCESS TO DBA;
GRANT ALTER ANY SQL TRANSLATION PROFILE TO DBA;
GRANT FLASHBACK ARCHIVE ADMINISTER TO DBA;
GRANT ALTER LOCKDOWN PROFILE TO DBA;
GRANT CREATE ATTRIBUTE DIMENSION TO DBA;
GRANT CREATE ANY ANALYTIC VIEW TO DBA;

-- Roles granted to DBA
--
-- DATAPUMP_IMP_FULL_DATABASE  (Role) 
--
GRANT DATAPUMP_IMP_FULL_DATABASE TO DBA;
--
-- XDBADMIN  (Role) 
--
GRANT XDBADMIN TO DBA;
--
-- SCHEDULER_ADMIN  (Role) 
--
GRANT SCHEDULER_ADMIN TO DBA;
--
-- OLAP_DBA  (Role) 
--
GRANT OLAP_DBA TO DBA;
--
-- EXECUTE_CATALOG_ROLE  (Role) 
--
GRANT EXECUTE_CATALOG_ROLE TO DBA;
--
-- OLAP_XS_ADMIN  (Role) 
--
GRANT OLAP_XS_ADMIN TO DBA;
--
-- CAPTURE_ADMIN  (Role) 
--
GRANT CAPTURE_ADMIN TO DBA;
--
-- EM_EXPRESS_ALL  (Role) 
--
GRANT EM_EXPRESS_ALL TO DBA;
--
-- SELECT_CATALOG_ROLE  (Role) 
--
GRANT SELECT_CATALOG_ROLE TO DBA;
--
-- EXP_FULL_DATABASE  (Role) 
--
GRANT EXP_FULL_DATABASE TO DBA;
--
-- WM_ADMIN_ROLE  (Role) 
--
GRANT WM_ADMIN_ROLE TO DBA;
--
-- GATHER_SYSTEM_STATISTICS  (Role) 
--
GRANT GATHER_SYSTEM_STATISTICS TO DBA;
--
-- OPTIMIZER_PROCESSING_RATE  (Role) 
--
GRANT OPTIMIZER_PROCESSING_RATE TO DBA;
--
-- JAVA_DEPLOY  (Role) 
--
GRANT JAVA_DEPLOY TO DBA;
--
-- DATAPUMP_EXP_FULL_DATABASE  (Role) 
--
GRANT DATAPUMP_EXP_FULL_DATABASE TO DBA;
--
-- XDB_SET_INVOKER  (Role) 
--
GRANT XDB_SET_INVOKER TO DBA;
--
-- JAVA_ADMIN  (Role) 
--
GRANT JAVA_ADMIN TO DBA;
--
-- IMP_FULL_DATABASE  (Role) 
--
GRANT IMP_FULL_DATABASE TO DBA;



