--
-- RESOURCE  (Role) 
--
CREATE ROLE RESOURCE NOT IDENTIFIED;

-- System privileges granted to RESOURCE
GRANT CREATE SEQUENCE TO RESOURCE;
GRANT CREATE TRIGGER TO RESOURCE;
GRANT CREATE CLUSTER TO RESOURCE;
GRANT CREATE INDEXTYPE TO RESOURCE;
GRANT CREATE TYPE TO RESOURCE;
GRANT CREATE OPERATOR TO RESOURCE;
GRANT CREATE TABLE TO RESOURCE;
GRANT CREATE PROCEDURE TO RESOURCE;

-- Roles granted to RESOURCE
--
-- SODA_APP  (Role) 
--
GRANT SODA_APP TO RESOURCE;



