--
-- TC_ADMIN_ROLE  (Role) 
--
CREATE ROLE TC_ADMIN_ROLE NOT IDENTIFIED;

-- Object privileges granted to TC_ADMIN_ROLE
GRANT UPDATE ON TOAD.TC_ALL_OBJECTS TO TC_ADMIN_ROLE;
GRANT DELETE ON TOAD.TC_ALL_OBJECTS TO TC_ADMIN_ROLE;
GRANT INSERT ON TOAD.TC_ALL_OBJECTS TO TC_ADMIN_ROLE;
GRANT SELECT ON TOAD.TC_ALL_OBJECTS TO TC_ADMIN_ROLE;
GRANT DELETE ON TOAD.TC_ALL_OBJ_MASK TO TC_ADMIN_ROLE;
GRANT INSERT ON TOAD.TC_ALL_OBJ_MASK TO TC_ADMIN_ROLE;
GRANT UPDATE ON TOAD.TC_ALL_OBJ_MASK TO TC_ADMIN_ROLE;
GRANT SELECT ON TOAD.TC_ALL_OBJ_MASK TO TC_ADMIN_ROLE;
GRANT INSERT ON TOAD.TC_CONFIG TO TC_ADMIN_ROLE;
GRANT SELECT ON TOAD.TC_CONFIG TO TC_ADMIN_ROLE;
GRANT UPDATE ON TOAD.TC_CONFIG TO TC_ADMIN_ROLE;
GRANT DELETE ON TOAD.TC_CONFIG TO TC_ADMIN_ROLE;
GRANT UPDATE ON TOAD.TC_FILEEXT TO TC_ADMIN_ROLE;
GRANT SELECT ON TOAD.TC_FILEEXT TO TC_ADMIN_ROLE;
GRANT DELETE ON TOAD.TC_GROUP TO TC_ADMIN_ROLE;
GRANT INSERT ON TOAD.TC_GROUP TO TC_ADMIN_ROLE;
GRANT SELECT ON TOAD.TC_GROUP TO TC_ADMIN_ROLE;
GRANT UPDATE ON TOAD.TC_GROUP TO TC_ADMIN_ROLE;
GRANT SELECT ON TOAD.TC_GROUP_ID TO TC_ADMIN_ROLE;
GRANT INSERT ON TOAD.TC_MASK TO TC_ADMIN_ROLE;
GRANT DELETE ON TOAD.TC_MASK TO TC_ADMIN_ROLE;
GRANT SELECT ON TOAD.TC_MASK TO TC_ADMIN_ROLE;
GRANT UPDATE ON TOAD.TC_MASK TO TC_ADMIN_ROLE;
GRANT UPDATE (PSL_FROZEN_TIMESTAMP) ON OLIVER.TC_OBJSTATUS TO TC_ADMIN_ROLE;
GRANT SELECT ON TOAD.TC_OBJSTATUS TO TC_ADMIN_ROLE;
GRANT INSERT ON TOAD.TC_OBJSTATUS TO TC_ADMIN_ROLE;
GRANT UPDATE ON TOAD.TC_OBJSTATUS TO TC_ADMIN_ROLE;
GRANT UPDATE (PSL_FROZEN_BY) ON OLIVER.TC_OBJSTATUS TO TC_ADMIN_ROLE;
GRANT UPDATE (PSL_FROZEN) ON OLIVER.TC_OBJSTATUS TO TC_ADMIN_ROLE;
GRANT DELETE ON TOAD.TC_OBJSTATUS TO TC_ADMIN_ROLE;
GRANT DELETE ON TOAD.TC_OBJSTATUS_VCS TO TC_ADMIN_ROLE;
GRANT INSERT ON TOAD.TC_OBJSTATUS_VCS TO TC_ADMIN_ROLE;
GRANT SELECT ON TOAD.TC_OBJSTATUS_VCS TO TC_ADMIN_ROLE;
GRANT UPDATE ON TOAD.TC_OBJSTATUS_VCS TO TC_ADMIN_ROLE;
GRANT SELECT ON TOAD.TC_SCRIPT_ID TO TC_ADMIN_ROLE;
GRANT SELECT ON TOAD.TC_TIMESTAMP TO TC_ADMIN_ROLE;
GRANT UPDATE ON TOAD.TC_TIMESTAMP TO TC_ADMIN_ROLE;
GRANT INSERT ON TOAD.TC_TIMESTAMP TO TC_ADMIN_ROLE;
GRANT DELETE ON TOAD.TC_TIMESTAMP TO TC_ADMIN_ROLE;
GRANT DELETE ON TOAD.TC_USERMAPPING TO TC_ADMIN_ROLE;
GRANT INSERT ON TOAD.TC_USERMAPPING TO TC_ADMIN_ROLE;
GRANT SELECT ON TOAD.TC_USERMAPPING TO TC_ADMIN_ROLE;
GRANT UPDATE ON TOAD.TC_USERMAPPING TO TC_ADMIN_ROLE;



