--
-- BI_DETAIL_TEMP  (Trigger) 
--
CREATE OR REPLACE TRIGGER OLIVER.BI_DETAIL_TEMP 
BEFORE INSERT ON OLIVER.TRANSACTION_DETAIL_TEMP
FOR EACH ROW
BEGIN
  select DETAIL_seq.nextval into :new.TDT_KEY from dual;
END;
/


