--
-- ACTIVE_EMPLOYERS  (View) 
--
CREATE OR REPLACE FORCE VIEW OLIVER.ACTIVE_EMPLOYERS
(CO_CLIENT, CO_PLAN, CO_NUMBER, CO_NAME)
AS 
(SELECT CO_CLIENT,CO_PLAN,CO_NUMBER,CO_NAME FROM TBL_COMPMAST WHERE (CO_CLIENT,CO_PLAN,CO_NUMBER) IN ((SELECT CP_CLIENT,CP_PLAN,CO_NUMBER FROM TBL_COMPPEN WHERE CP_CLIENT=CO_CLIENT AND CP_PLAN=CO_PLAN AND CP_NUMBER=CO_NUMBER AND CP_TERM_DATE  IS NULL) UNION (SELECT CH_CLIENT_ID,CH_PLAN,CH_NUMBER FROM TBL_COMPHW WHERE CH_CLIENT_ID=CO_CLIENT AND CH_PLAN=CO_PLAN AND CH_NUMBER=CO_NUMBER AND CH_TERM_DATE  IS NULL)));


