--
-- BOT_GET_AVAILABLE_AMOUNTS  (View) 
--
CREATE OR REPLACE FORCE VIEW OLIVER.BOT_GET_AVAILABLE_AMOUNTS
(CL_ID, AVAILABLE_AMT)
AS 
select cl_id, TO_CHAR(CLAIMS.GET_AVAILABLE_AMT('ADJ1', cl_id, CLAIMS.GET_PLAN_MEMBER_IDENTIFIER('ADJ1', 'SUMA'), SYSDATE, NULL, cl_claim_number, NULL, 'SUMA'), '$9999') available_amt from tbl_claims;


