--
-- DEPOSIT_SLIP_TEST1  (View) 
--
CREATE OR REPLACE FORCE VIEW OLIVER.DEPOSIT_SLIP_TEST1
(PLAN_TYPE, CLIENTID, PLANID, EMPLOYER, EMPLOYER_NAME, 
 CONTRIBUTION_START_DATE, CONTRIBUTION_END_DATE, CONTRIBUTION_PERIOD, PAYMENT_RECD_AMOUNT, PAYMENT_TYPE, 
 TH_TRAN_ID, PAYMENT_REFERENCE, POSTED_DATE)
AS 
(
SELECT 'HW' PLAN_TYPE, 
       TH_CLIENT_ID CLIENTID, 
       TH_PLAN_ID PLANID, 
       TH_EMPLOYER EMPLOYER, 
       CO_NAME EMPLOYER_NAME, 
       TH_START_DATE CONTRIBUTION_START_DATE, 
       TH_END_DATE CONTRIBUTION_END_DATE, 
       TH_PERIOD CONTRIBUTION_PERIOD, 
       TH_AMOUNT PAYMENT_RECD_AMOUNT, 
       TH_PAYMENT_TYPE PAYMENT_TYPE, 
       TH_TRAN_ID, 
       TH_CHEQUE PAYMENT_REFERENCE, 
       TH_POSTED_DATE POSTED_DATE 
  FROM TRANSACTION_HEADER, 
       TBL_COMPMAST TBL_COMPMAST1 
 WHERE TH_CLIENT_ID = CO_CLIENT 
   AND TH_PLAN_ID = CO_PLAN 
   AND TH_EMPLOYER = CO_NUMBER 
   AND TH_DEPOSIT_NUMBER IS NULL 
UNION ALL 
SELECT /*+ FULL(TBL_COMPMAST2) */ 'PENSION' PLAN_TYPE, 
       THP_CLIENT_ID, 
       THP_PLAN_ID, 
       THP_EMPLOYER, 
       CO_NAME, 
       THP_START_DATE, 
       THP_END_DATE, 
       THP_PERIOD, 
       THP_AMOUNT, 
       THP_PAYMENT_TYPE, 
       THP_TRAN_ID, 
       THP_CHEQUE, 
       THP_POSTED_DATE 
  FROM TRANSACTION_HEADER_PEN, 
       TBL_COMPMAST TBL_COMPMAST2 
 WHERE THP_CLIENT_ID = CO_CLIENT 
   AND THP_PLAN_ID = CO_PLAN 
   AND THP_EMPLOYER = CO_NUMBER 
   AND THP_DEPOSIT_NUMBER IS NULL 
UNION ALL 
SELECT 'OTHER FUNDS' PLAN_TYPE, 
       THF_CLIENT_ID, 
       THF_PLAN_ID, 
       THF_EMPLOYER, 
       CO_NAME, 
       THF_START_DATE, 
       THF_END_DATE, 
       THF_PERIOD, 
       THF_AMOUNT, 
       THF_PAYMENT_TYPE, 
       THF_TRAN_ID, 
       THF_CHEQUE, 
       THF_POSTED_DATE 
  FROM TRANSACTION_HEADER_FUNDS, 
       TBL_COMPMAST TBL_COMPMAST3 
 WHERE THF_CLIENT_ID = CO_CLIENT 
   AND THF_PLAN_ID = CO_PLAN 
   AND THF_EMPLOYER = CO_NUMBER 
   AND THF_DEPOSIT_NUMBER IS NULL
);


