--
-- HW_PAYMENTS_RECD  (View) 
--
CREATE OR REPLACE FORCE VIEW OLIVER.HW_PAYMENTS_RECD
(TH_CLIENT_ID, TH_PLAN_ID, EMPLOER_ID, CO_NAME, TH_CHEQUE, 
 TH_AMOUNT, TH_PAYMENT_TYPE, TH_POSTED_DATE)
AS 
(SELECT TH_CLIENT_ID,TH_PLAN_ID,TH_EMPLOYER EMPLOER_ID,CO_NAME,TH_CHEQUE,TH_AMOUNT,TH_PAYMENT_TYPE,TH_POSTED_DATE FROM TRANSACTION_HEADER,TBL_COMPMAST WHERE TH_CLIENT_ID=CO_CLIENT AND CO_PLAN=TH_PLAN_ID AND CO_NUMBER=TH_EMPLOYER AND  NVL(TH_AMOUNT,0)>0 AND TH_PAYMENT_TYPE IS NOT NULL);


