--
-- PEN_ANNUAL_VW_POC  (View) 
--
CREATE OR REPLACE FORCE VIEW OLIVER.PEN_ANNUAL_VW_POC
(TD_CLIENT_ID, TD_PLAN_ID, TD_EMPLOYER, CO_NAME, TD_MEM_ID, 
 MEM_LAST_NAME, MEM_FIRST_NAME, YEAR, HOURS, EE_CONTS, 
 ER_CONTS, CREDITED_SERVICE)
AS 
(select TD_CLIENT_ID,td_plan_id,td_employer,co_name,td_mem_id,mem_last_name,mem_first_name,TO_NUMBER(TO_CHAR(TD_PERIOD,'RRRR')) Year,SUM(TDT_UNITS) HOURS,SUM(DECODE(tdT_EE_units,0,0,TDT_AMOUNT)) EE_CONTS,SUM(DECODE(tdT_ER_units,0,0,TDT_AMOUNT)) ER_CONTS,(SELECT SUM(TDT_AMOUNT) from DAT_CONTRIBS WHERE PERSON_ID=MEM_ID AND ORGANS_ID=CO_NUMBER AND TO_NUMBER(TO_CHAR(TO_DATE(EFFECTE_DATE,'MM/DD/RRRR'),'RRRR'))=TO_NUMBER(TO_CHAR(TD_PERIOD,'RRRR'))  AND UPPER(NVL(LTRIM(RTRIM(TRANS_TYPE)),'XX'))='CS'),(SELECT SUM(TDT_AMOUNT) from DAT_CONTRIBS WHERE PERSON_ID=MEM_ID AND ORGANS_ID=CO_NUMBER AND TO_NUMBER(TO_CHAR(TO_DATE(EFFECTE_DATE,'MM/DD/RRRR'),'RRRR'))=TO_NUMBER(TO_CHAR(TD_PERIOD,'RRRR'))  AND UPPER(NVL(LTRIM(RTRIM(TRANS_TYPE)),'XX'))='CS') FROM transaction_detail,tbl_compmast,tbl_member where co_plan=mem_plan and NVL(TDT_PEN_UNITS,0)<>0  AND td_mem_id=mem_id and co_plan=td_plan_id and co_number=td_employer GROUP BY TD_CLIENT_ID,td_plan_id,td_employer,co_name,td_mem_id,mem_last_name,mem_first_name,TO_NUMBER(TO_CHAR(TD_PERIOD,'RRRR')));


