--
-- PEN_INACTIVITY_EMPLOYERS  (View) 
--
CREATE OR REPLACE FORCE VIEW OLIVER.PEN_INACTIVITY_EMPLOYERS
(CO_CLIENT, CO_PLAN, ER_ID, ER_NAME, LRD)
AS 
(select CO_CLIENT,CO_plan,CO_NUMBER ER_ID,CO_NAME ER_NAME, PENSION_PKG.get_pEN_ER_lrd(CO_CLIENT,CO_PLAN,CO_NUMBER,SYSDATE) LRD from tbl_COMPPEN,tbl_compmast  where CO_CLIENT=CP_CLIENT AND CO_PLAN=CP_PLAN AND  CP_TERM_DATE IS NULL AND  PENSION_PKG.get_pen_ER_lrd(CO_CLIENT,CO_PLAN,CO_NUMBER,SYSDATE)<ADD_MONTHS(SYSDATE,-18));


