--
-- TBL_DOCUMENT_REPO_SEQ  (Sequence) 
--
CREATE SEQUENCE OLIVER.TBL_DOCUMENT_REPO_SEQ
  START WITH 16
  MAXVALUE 999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
  NOKEEP
  GLOBAL;


