--
-- TBL_DOCUMENT_REPO_TYPE_SEQ  (Sequence) 
--
CREATE SEQUENCE OLIVER.TBL_DOCUMENT_REPO_TYPE_SEQ
  START WITH 4
  MAXVALUE 999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
  NOKEEP
  GLOBAL;


