--
-- DATA_LOAD_POC  (Procedure) 
--
CREATE OR REPLACE PROCEDURE OLIVER.data_load_POC AS
BEGIN
insert into tbl_member(MEM_CLIENT_ID,MEM_PLAN,MEM_ID,MEM_LAST_NAME,MEM_FIRST_NAME,MEM_MIDDLE_NAME,MEM_ADDRESS1,MEM_ADDRESS2,MEM_CITY,MEM_PROV,MEM_COUNTRY,MEM_POSTAL_CODE,MEM_HOME_PHONE,MEM_WORK_PHONE,MEM_CELL_PHONE,MEM_FAX,MEM_DOB,MEM_DOD,MEM_GENDER,MEM_TITLE,MEM_CREATED_DATE,MEM_LAST_MODIFIED_DATE,MEM_LANG_PREF)  (SELECT 'DT','GOT',ltrim(rtrim(PERSON_ID)),UPPER(LAST_NAME),UPPER(FIRST_NAME),UPPER(INITIAL1),UPPER(ADDR1),UPPER(LTRIM(RTRIM(ADDR2||' '||ADDR3))),UPPER(CITY),UPPER(PROV_STATE),UPPER(COUNTRY),UPPER(POSTALCODE),RES_PHONE,BUS_PHONE,CEL_PHONE,FAX_PHONE,BIRTHDATE,DEATHDATE,UPPER(GENDER),TITLE,CREATEDATE,LASTEDIT,UPPER(LANGUAGE) FROM DAT_PERSONS1 WHERE PERSON_ID IN (SELECT PERSON_ID FROM DAT_PENMEM));
UPDATE TBL_MEMBER SET MEM_SIN=  (SELECT SIN FROM DAT_PERSONS1 WHERE PERSON_ID=MEM_ID AND PERSON_ID IN (SELECT PERSON_ID FROM DAT_PENMEM));

--INSERT INTO TBL_PENMAST(PENM_ID,PENM_PLAN,PENM_ENTRY_DATE,PENM_HIRE_DATE,PENM_STATUS,PENM_STATUS_DATE,PENM_RECIPROCAL,PENM_LOCAL,PENM_EMPLOYER,PENM_PAST_SERV,PENM_PAST_PENSION,PENM_CURR_SERV,PENM_CURR_PENSION,PENM_MARITAL_STATUS,PENM_LRD,PENM_VP_PENSION,PENM_PROCESS_DATE,penm_client ,penm_vetsed_date) (SELECT ltrim(rtrim(DAT_PENMEM.PERSON_ID)),'GOT' PENM_PLAN,START_DATE,JOINDATE,null,null,null,LOCAL,null,past_yrs,pS_PEN,curr_yrs,earned_pen,MARITAL,null,0,null,'DT',VEST_DATE FROM DAT_PENMEM,DAT_PERSONS1 WHERE DAT_PENMEM.PERSON_ID=DAT_PERSONS1.PERSON_ID);
INSERT INTO TBL_PENMAST(PENM_ID,PENM_PLAN,PENM_ENTRY_DATE,PENM_HIRE_DATE,PENM_STATUS,PENM_STATUS_DATE,PENM_RECIPROCAL,PENM_LOCAL,PENM_EMPLOYER,PENM_PAST_SERV,PENM_PAST_PENSION,PENM_CURR_SERV,PENM_CURR_PENSION,PENM_MARITAL_STATUS,PENM_LRD,PENM_VP_PENSION,PENM_PROCESS_DATE,penm_client ,penm_vetsed_date) (SELECT ltrim(rtrim(DAT_PENMEM.PERSON_ID)),'GOT' PENM_PLAN,TO_DATE(START_DATE,'MM/DD/RRRR'),TO_DATE(JOINDATE,'MM/DD/RRRR'),null,null,null,LOCAL,null,past_yrs,pS_PEN,curr_yrs,earned_pen,MARITAL,null,0,null,'DT',TO_DATE(VEST_DATE,'MM/DD/RRRR') FROM DAT_PENMEM,DAT_PERSONS1 WHERE DAT_PENMEM.PERSON_ID=DAT_PERSONS1.PERSON_ID);

Insert into CDATV5.TBL_PEN_BENEFICIARY (PB_PLAN,PB_ID,PB_BEN_NO,PB_LAST_NAME,PB_FIRST_NAME,PB_DOB,PB_RELATION,PB_BE_PER,PB_EFF_DATE,PB_TERM_DATE,PB_SEX,PB_LAST_MODIFIED_BY,PB_LAST_MODIFIED_DATE,PB_KEY,PB_BENEFIT,PB_MPE,PB_WITHDRAW,PB_WITHDRAW_DATE,PB_ADDRESS1,PB_ADDESS2,PB_CITY,PB_PROV,PB_COUNTRY,PB_BEN_ID,PB_BEN_SIN,PB_CLIENT,PB_MIDDLE_NAME) 
SELECT 'GOT',ltrim(rtrim(DAT_BENEFICS.AFFIL_ID)),NULL,UPPER(LAST_NAME),UPPER(FIRST_NAME),BIRTHDATE,UPPER(RELATION),NULL,RELATNDATE,CANCELDATE,UPPER(GENDER),NULL,LASTEDIT,ROWNUM,NULL,NULL,NULL,NULL,UPPER(ADDR1),UPPER(LTRIM(RTRIM(ADDR2||' '||ADDR3||' '||CITY))),UPPER(PROV_STATE),UPPER(COUNTRY),UPPER(POSTALCODE),NULL,NULL,'DT',UPPER(DAT_PERSONS1.INITIAL1)FROM DAT_PERSONS1,DAT_BENEFICS WHERE ltrim(rtrim(DAT_PERSONS1.PERSON_ID))=ltrim(rtrim(DAT_BENEFICS.person_ID));

Insert into CDATV5.TBL_RETIREES (RET_MEM_ID,RET_CLIENT_ID,RET_PLAN_ID,RET_RETIRE_DATE,RET_PEN_OPTION,RET_PEN_TYPE,RET_PEN_AMT,RET_BRIDGE_AMT,RET_GTEE_MTHS,RET_SURVIVOR_PER,RET_SURVIVOR_SIN,RET_END_GTEE_DATE,RET_SUPP1_AMT  ,RET_SUPP2_AMT ,RET_RED_AMT,RET_TAX_CODE,RET_CREATED_DATE ,RET_CREATED_BY,RET_MODIFIED_DATE ,RET_MODIFIED_BY)
(SELECT DAT_PENSNERS.PERSON_ID,'DT','GOT',TO_DATE(DAT_PENSNERS.STARTDATE,'MM/DD/RRRR'),DAT_PENSNERS.FORM,DAT_PENSNERS.TYPE,MONTHLYAMT,0,GUARANTEE,SURVPERCNT,NULL,NULL,SUPPLEMENT,0,REDUCTION,NULL,TO_DATE(DAT_PENSNERS.LASTCHANGE,'MM/DD/RRRR'),DAT_PENSNERS.USERID ,TO_DATE(DAT_PENSNERS.LASTCHANGE,'MM/DD/RRRR'),DAT_PENSNERS.USERID FROM DAT_PENSNERS,DAT_PERSONS1 WHERE  ltrim(rtrim(DAT_PENSNERS.PERSON_ID))=ltrim(rtrim(DAT_PERSONS1.PERSON_ID)));
insert into tbl_mem_units(MPU_ID,MPU_PLAN,MPU_UNITS,MPU_FUND,MPU_RATE,MPU_AMT,MPU_FROM,MPU_TO,MPU_PERIOD,MPU_ENTERED_DATE,MPU_EMPLOYER,MPU_USER,MU_BATCH,MU_DESC,MU_CLIENT,TRANS_TYPE,UNITS_TYPE) select ltrim(rtrim(person_id)),'GOT',UNITS,'PEN',RATE,AMOUNT,TRUNC(TO_DATE(EFFECTDATE,'MM/DD/RRRR'),'MM'),TO_DATE(EFFECTDATE,'MM/DD/RRRR'),TO_DATE(EFFECTDATE,'MM/DD/RRRR'),TO_DATE(ENTRYDATE,'MM/DD/RRRR'),ORGANS_ID,NULL,BATCH_ID,NULL,'DT',TRANSTYPE,UNITS_TYPE FROM DAT_CONTRIBS WHERE  NVL(UPPER(LTRIM(RTRIM(TRANSTYPE))),'XX') IN ('AF', 'EC', 'ED', 'EE', 'ES', 'EY', 'EZ', 'E2', 'E4', 'IE', 'IJ', 'NM', 'PT', 'RI', 'RO', 'SE', 'SH', 'ST', 'S1', 'TS', 'ZE','RA', 'TB', 'TC', 'RD', 'RE', 'RZ', 'SR', 'TR', 'TT', 'ZR');

--insert into tbl_mem_units(MPU_ID,MPU_PLAN,MPU_UNITS,MPU_FUND,MPU_RATE,MPU_AMT,MPU_FROM,MPU_TO,MPU_PERIOD,MPU_ENTERED_DATE,MPU_EMPLOYER,MPU_USER,MU_BATCH,MU_DESC,MU_CLIENT,TRANS_TYPE,UNITS_TYPE) (select ltrim(rtrim(person_id)),'GOT',UNITS,'PEN',RATE,AMOUNT,TRUNC(TO_DATE(EFFECTDATE,'MM/DD/RRRR'),'MM'),TO_DATE(EFFECTDATE,'MM/DD/RRRR'),TO_DATE(EFFECTDATE,'MM/DD/RRRR'),TO_DATE(ENTRYDATE,'MM/DD/RRRR'),ORGANS_ID,NULL,BATCH_ID,NULL,'DT',TRANSTYPE,UNITS_TYPE FROM DAT_CONTRIBS);
INSERT INTO TBL_COMPMAST(CO_NUMBER,CO_DIV,CO_NAME,CO_PLAN,CO_CLIENT,CO_TYPE,CO_CREATED_DATE ,CO_CREATED_BY ,CO_EDITED_DATE ,CO_EDITED_BY ) (SELECT LTRIM(RTRIM(ORGANS_ID)),'00',NAME,'GOT','DT',TYPE,CREATEDATE,NULL,LASTEDIT,NULL FROM DAT_ORGANS);
INSERT INTO TBL_COMPPEN(CP_NUMBER,CP_DIV,CP_CONTACT,CP_ADDRESS1,CP_ADDRESS2,CP_CITY,CP_PROV,CP_COUNTRY,CP_POST_CODE,CP_PHONE1,CP_PHONE2,CP_FAX,CP_EMAIL1,CP_EMAIL2,CP_LANG_PREF,CP_PLAN,CP_LAST_MODIFIED_BY,CP_LAST_MODIFIED_DATE,CP_OS_BAL,CP_EFF_DATE,CP_TERM_DATE,CP_LRD,CP_WORK_PROV,CP_CLIENT,CP_CREATED_DATE,CP_CREATED_BY ) (SELECT LTRIM(RTRIM(ORGANS_ID)),'00',NULL,UPPER(BUS_ADDR1),UPPER(BUS_ADDR2||' '||BUS_ADDR3),BUS_CITY,BUS_PROV,BUS_COUNT,BUS_POST,TEL1_PHONE,TEL2_PHONE,NULL,NULL,NULL,LANGUAGE,'GOT',NULL,TO_DATE(LASTEDIT,'MM/DD/RRRR'),NULL,NULL,NULL,NULL,BUS_PROV,'DT',CREATEDATE,NULL FROM DAT_ORGANS);



INSERT INTO TRANSACTION_HEADER_PEN(THP_EMPLOYER,THP_PLAN_ID,THP_START_DATE,THP_END_DATE,THP_PERIOD,THP_CLIENT_ID,THP_TRAN_ID) (SELECT ORGANS_ID,'GOT',START_DATE,END_DATE,EFFECTDATE,'DT',BATCH_ID FROM DAT_BATCHES);
update transaction_header_pen set thp_amount=(select sum(mpu_amt) from tbl_mem_units where mpu_employer=thp_employer and mu_batch=thp_tran_id) where thp_plan_ID='GOT'; 
update transaction_header_pen set thp_units=(select sum(mpu_units) from tbl_mem_units where mpu_employer=thp_employer and mu_batch=thp_tran_id) where thp_plan_ID='GOT'; 
update transaction_header_pen set thp_rate=(select avg(mpu_rate) from tbl_mem_units where mpu_employer=thp_employer and mu_batch=thp_tran_id) where thp_plan_ID='GOT'; 


Insert into TBL_EMPLOYER_CONTACTS (TEC_CLIENT,TEC_ID,TEC_DIV,TEC_LOC,TEC_CONTACT,TEC_ADDRESS1,TEC_ADDRESS2,TEC_CITY,TEC_POST_CODE,TEC_COUNTRY,TEC_PHONE1,TEC_PHONE2,TEC_EMAIL1,TEC_EMAIL2,TEC_FAX,TEC_PRIMARY,TEC_NOTE,TEC_PROV,TEC_LAST_MODIFIED_BY,TEC_LAST_MODIFIED_DATE,TEC_PLAN,TEC_EFFECTIVE_DATE,TEC_TERM_DATE,TEC_KEY)

(SELECT 'DT',CP_NUMBER,CP_DIV,0,CP_CONTACT,CP_ADDRESS1,CP_ADDRESS2,CP_CITY,CP_POST_CODE,CP_COUNTRY,CP_PHONE1,CP_PHONE2,CP_EMAIL1,CP_EMAIL2,CP_FAX,'Y',NULL,CP_PROV,CP_LAST_MODIFIED_BY,CP_LAST_MODIFIED_DATE,CP_PLAN,CP_EFF_DATE,CP_TERM_DATE,CP_NUMBER FROM TBL_COMPPEN WHERE CP_PLAN='GOT');



DELETE FROM TBL_EMPLOYMENT_HIST WHERE TEH_PLAN='GOT';
Insert into TBL_EMPLOYMENT_HIST (TEH_ID,TEH_ER_ID,TEH_EFF_DATE,TEH_PLAN,TEH_CLIENT) (SELECT DISTINCT MPU_ID,MPU_EMPLOYER,MIN(MPU_PERIOD),'GOT','DT' FROM TBL_MEM_UNITS WHERE MPU_PLAN='GOT' AND LTRIM(RTRIM(MPU_EMPLOYER)) IS NOT NULL GROUP BY MPU_ID,MPU_EMPLOYER,'GOT','DT');

--Insert into TBL_EMPLOYMENT_HIST (TEH_ID,TEH_ER_ID,TEH_EFF_DATE,TEH_PLAN,TEH_CLIENT) (SELECT DISTINCT MPU_ID,MPU_EMPLOYER,MIN(MPU_PERIOD),'GOT','DT' FROM TBL_MEM_UNITS WHERE MPU_PLAN='GOT' AND MPU_EMPLOYER IS NOT NULL GROUP BY MPU_ID,MPU_EMPLOYER,'GOT','DT');
--INSERT INTO TRANSACTION_DETAIL (TD_MEM_ID,TD_PLAN_ID,TDT_PEN_UNITS,TD_AMOUNT,TD_START_DATE,TD_END_DATE,TD_PERIOD,TD_POSTED_DATE,TD_EMPLOYER,TD_USER,TD_TRAN_ID,TD_CLIENT_ID) (SELECT MPU_ID,MPU_PLAN,MPU_UNITS,MPU_AMT,MPU_FROM,MPU_TO,MPU_PERIOD,MPU_ENTERED_DATE,MPU_EMPLOYER,MPU_USER,MU_BATCH,MU_CLIENT FROM TBL_MEM_UNITS WHERE MPU_PLAN='GOT');
INSERT INTO TRANSACTION_DETAIL (TD_MEM_ID,TD_PLAN_ID,TDT_PEN_UNITS,TD_AMOUNT,TD_START_DATE,TD_END_DATE,TD_PERIOD,TD_POSTED_DATE,TD_EMPLOYER,TD_USER,TD_TRAN_ID,TD_CLIENT_ID,TD_UNITS_TYPE,TDT_ER_UNITS,TDT_EE_UNITS) (SELECT MPU_ID,MPU_PLAN,MPU_UNITS,MPU_AMT,MPU_FROM,MPU_TO,MPU_PERIOD,MPU_ENTERED_DATE,MPU_EMPLOYER,MPU_USER,MU_BATCH,MU_CLIENT,UNITS_TYPE,MPU_UNITS,0 FROM TBL_MEM_UNITS WHERE MPU_PLAN='GOT' AND  UPPER(NVL(LTRIM(RTRIM(TRANS_TYPE)),'XX')) IN ('AF', 'EC', 'ED', 'EE', 'ES', 'EY', 'EZ', 'E2', 'E4', 'IE', 'IJ', 'NM', 'PT', 'RI', 'RO', 'SE', 'SH', 'ST', 'S1', 'TS', 'ZE')) UNION ALL (SELECT MPU_ID,MPU_PLAN,MPU_UNITS,MPU_AMT,MPU_FROM,MPU_TO,MPU_PERIOD,MPU_ENTERED_DATE,MPU_EMPLOYER,MPU_USER,MU_BATCH,MU_CLIENT,UNITS_TYPE,0,MPU_UNITS FROM TBL_MEM_UNITS WHERE MPU_PLAN='GOT' AND  UPPER(NVL(LTRIM(RTRIM(TRANS_TYPE)),'XX')) NOT IN ('AF', 'EC', 'ED', 'EE', 'ES', 'EY', 'EZ', 'E2', 'E4', 'IE', 'IJ', 'NM', 'PT', 'RI', 'RO', 'SE', 'SH', 'ST', 'S1', 'TS', 'ZE')) ;
INSERT INTO TBL_ANNUAL( ANN_CLIENT,ANN_PLAN,ANN_ID,ANN_YEAR,ANN_HRS,ANN_EE_CONTS,ANN_ER_CONTS) (select TD_CLIENT_ID,td_plan_id,Td_mem_id,TO_NUMBER(TO_CHAR(TD_PERIOD,'RRRR')) Year,SUM(TDT_PEN_UNITS) HOURS,SUM(DECODE(tdT_EE_units,0,0,TD_AMOUNT)) EE_CONTS,SUM(DECODE(tdT_ER_units,0,0,TD_AMOUNT)) ER_CONTS FROM transaction_detail where  NVL(TDT_PEN_UNITS,0)<>0   GROUP BY TD_CLIENT_ID,td_plan_id,TD_MEM_ID,TO_NUMBER(TO_CHAR(TD_PERIOD,'RRRR')));
UPDATE TBL_ANNUAL SET ANN_CRED_SERV=(SELECT SUM(AMOUNT) from DAT_CONTRIBS WHERE PERSON_ID=ANN_ID  AND TO_NUMBER(TO_CHAR(TO_DATE(EFFECTDATE,'MM/DD/RRRR'),'RRRR'))=ANN_YEAR  AND UPPER(NVL(LTRIM(RTRIM(TRANSTYPE)),'XX'))='CS');
update tbl_annual set ann_pen_value=(select sum(amount) from dat_credits where person_id=ann_id and LTRIM(RTRIM(TRANSTYPE)) NOT IN ('HW') AND  ann_year=to_number(to_char(to_date(effectdate,'mm/dd/rrrr'),'rrrr')));


update tbl_penmAST set penm_status=(select max(a.status) from dat_penstat a where ltrim(rtrim(a.person_id))=ltrim(rtrim(penm_id)) and to_date(a.statusdate,'mm/dd/rrrr')=(select max(to_date(b.statusdate,'mm/dd/rrrr')) from dat_penstat b where ltrim(rtrim(b.person_id))=penm_id)),penm_status_date=(select distinct to_date(a.statusdate,'mm/dd/rrrr') from dat_penstat a where ltrim(rtrim(a.person_id))=penm_id and to_date(a.statusdate,'mm/dd/rrrr')=(select max(to_date(b.statusdate,'mm/dd/rrrr')) from dat_penstat b where ltrim(rtrim(b.person_id))=penm_id)) where penm_plan='GOT';
 UPDATE TBL_PENMAST SET PENM_CURR_PENSION=(SELECT SUM(ANN_PEN_VALUE) FROM TBL_ANNUAL WHERE ANN_CLIENT=PENM_CLIENT AND ANN_PLAN=PENM_PLAN AND ANN_ID=PENM_ID);
--CREATE TABLE TBL_BENEFIC_RELATION AS (SELECT 'DT' TBR_CLIENT,'GOT' TBR_PLAN,LTRIM(RTRIM(TBCLOOKUP)) TBR_REL_CODE,LTRIM(RTRIM(TBCDESC)) TBR_REL_DESC FROM DAT_TABLES WHERE LTRIM(RTRIM(TBCTYPE))='GRL');
DELETE FROM TRANSACTION_DETAIL_TEMP WHERE NVL(TDT_PLAN_ID,'XXX')<>'GOT';

Insert into CDATV5.TBL_AGREEMENT (TA_ID,TA_DESC,TA_PLAN_ID,TA_CLIENT_ID,TA_EFF_DATE) (select DISTINCT agree_id,agr_code,'GOT','DT',TO_DATE(EFFECTDATE,'MM/DD/RRRR') FROM DAT_AGREEMNT);
Insert into CDATV5.TBL_AGREEMENT_DETAILS (TAD_FUND,TAD_KEY,TAD_AGREE_ID,TAD_ER_ID,TAD_OCCUP_ID,TAD_YEAR_ID,TAD_EFF_DATE,TAD_UNIT_TYPE,TAD_RATE,TAD_CLIENT_ID,TAD_PLAN_ID) (SELECT DISTINCT FUND,ROWNUM,DAT_AGREEMNT.AGREE_ID,NULL,NULL,0,TO_DATE(EFFECTDATE,'MM/DD/RRRR'),FUNDTYPE,NVL(RATE1,0)+NVL(RATE2,0)+NVL(RATE3,0)+NVL(RATE4,0),'DT','GOT' FROM DAT_TBLAGREEMENTSTERM1,DAT_AGREEMNT  WHERE DAT_TBLAGREEMENTSTERM1.AGREE_ID=DAT_AGREEMNT.AGREE_ID ); 
Insert into CDATV5.TBL_EMPLOYER_AGREEMENTS (TEA_CLT_ID,TEA_PLAN_ID,TEA_ER_ID,TEA_AGREEMENT_ID,TEA_EFF_DATE,TEA_TERM_DATE,TEA_CREATED_BY,TEA_CREATED_DATE,TEA_ID,IS_DELETED) (SELECT DISTINCT 'DT','GOT',ORGANS_ID,AGREE_ID,TO_DATE(EFFECTDATE,'MM/DD/RRRR'),TO_DATE(EXPIRYDATE,'MM/DD/RRRR'),NULL,TO_DATE(CREATEDATE,'MM/DD/RRRR'),ROWNUM,NULL FROM DAT_AGREEMNT);
INSERT INTO TBl_AGREEMENT_DESC (select distinct ta_desc TADC_CODE ,TBCDESC TADC_DESC from tbl_agreement,DAT_TABLES WHERE UPPER(LTRIM(RTRIM(TA_DESC)))=UPPER(LTRIM(RTRIM(TBCLOOKUP))) AND TBCTYPE='PBT');

---PLEASE COMMENT PENMAST LOOKUP IN GET_PEN_EMPLOYER FUNCTION BEFORE BELOW
update tbl_penmast set penm_employer=pension_pkg.GET_PEN_EMPLOYER('DT','GOT',PENM_ID ,SYSDATE) ;
update transaction_header_pen set thp_period=nvl(thp_period,thp_end_date) where thp_period is null;
UPDATE TBL_EMPLOYMENT_HIST SET TEH_UNION_LOCAL=  (SELECT LOCAL FROM DAT_PERSONS1 WHERE PERSON_ID=TEH_ID AND PERSON_ID IN (SELECT PERSON_ID FROM DAT_PENMEM));

END;
/

