--
-- BENEFITS_DEP_BASED_INDEX1  (Index) 
--
CREATE INDEX OLIVER.BENEFITS_DEP_BASED_INDEX1 ON OLIVER.BENEFITS_DEP_BASED
(BDB_CLIENT_ID, BDB_PLAN_ID, BDB_CLASS, BDB_BENEFIT)
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           );


