--
-- SYS_MTABLE_000015FA2_IND_3  (Index) 
--
CREATE INDEX OLIVER.SYS_MTABLE_000015FA2_IND_3 ON OLIVER.SYS_EXPORT_SCHEMA_02
(BASE_PROCESS_ORDER)
TABLESPACE CDATV5DATAFILE
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           );


