--
-- SYS_MTABLE_000018FF9_IND_2  (Index) 
--
CREATE INDEX OLIVER.SYS_MTABLE_000018FF9_IND_2 ON OLIVER.SYS_EXPORT_SCHEMA_01
(BASE_PROCESS_ORDER)
TABLESPACE CDATV5DATAFILE
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           );


