--
-- SYS_MTABLE_00002531C_IND_1  (Index) 
--
CREATE INDEX OLIVER.SYS_MTABLE_00002531C_IND_1 ON OLIVER.SYS_EXPORT_SCHEMA_05
(OBJECT_SCHEMA, ORIGINAL_OBJECT_NAME, OBJECT_TYPE)
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           );


