--
-- TBL_EMPLOYER_FUND_RATES_PK  (Index) 
--
CREATE UNIQUE INDEX OLIVER.TBL_EMPLOYER_FUND_RATES_PK ON OLIVER.TBL_EMPLOYER_FUND_RATES
(PFR_CLIENT_ID, PFR_PLAN_ID, PFR_EMPLOYER, PFR_FUND_ID, PFR_EFF_DATE)
TABLESPACE CDATV5DATAFILE
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           );


