--
-- TRANSACTION_HEADER_PEN_INDEX2  (Index) 
--
CREATE INDEX OLIVER.TRANSACTION_HEADER_PEN_INDEX2 ON OLIVER.TRANSACTION_HEADER_PEN
(THP_CLIENT_ID, THP_PLAN_ID, THP_EMPLOYER)
TABLESPACE CDATV5DATAFILE
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           );


