-- 
-- Non Foreign Key Constraints for Table APEX_ACCESS_CONTROL 
-- 
ALTER TABLE OLIVER.APEX_ACCESS_CONTROL ADD (
  CONSTRAINT APEX_ACCESS_CONTROL_PK
  PRIMARY KEY
  (ID)
  USING INDEX OLIVER.APEX_ACCESS_CONTROL_PK
  ENABLE VALIDATE);

