-- 
-- Non Foreign Key Constraints for Table APP_DEPLOYMENT_OBJECT 
-- 
ALTER TABLE OLIVER.APP_DEPLOYMENT_OBJECT ADD (
  CONSTRAINT APP_DEPLOYMENT_OBJECT_PK
  PRIMARY KEY
  (SCRIPT_ID)
  USING INDEX OLIVER.APP_DEPLOYMENT_OBJECT_PK
  ENABLE VALIDATE);

