-- 
-- Non Foreign Key Constraints for Table BENEFITS_VOLUME_BASED 
-- 
ALTER TABLE OLIVER.BENEFITS_VOLUME_BASED ADD (
  CONSTRAINT BENEFITS_VOLUME_BASED_PK
  PRIMARY KEY
  (BVB_CLIENT_ID, BVB_PLAN_ID, BVB_BENEFIT, BVB_CLASS, BVB_EFFECTIVE_DATE)
  DISABLE NOVALIDATE);

