-- 
-- Non Foreign Key Constraints for Table BENEFITS_DEP_BASED 
-- 
ALTER TABLE OLIVER.BENEFITS_DEP_BASED ADD (
  CONSTRAINT BENEFITS_DEP_BASED_PK
  PRIMARY KEY
  (BDB_CLIENT_ID, BDB_PLAN_ID, BDB_BENEFIT, BDB_DEP_STATUS, BDB_CLASS, BDB_EFF_DATE)
  DISABLE NOVALIDATE);

