-- 
-- Non Foreign Key Constraints for Table DEMO_CUSTOMERS 
-- 
ALTER TABLE OLIVER.DEMO_CUSTOMERS ADD (
  CONSTRAINT DEMO_CUST_CREDIT_LIMIT_MAX
  CHECK (credit_limit <= 5000)
  ENABLE VALIDATE);

ALTER TABLE OLIVER.DEMO_CUSTOMERS ADD (
  CONSTRAINT DEMO_CUSTOMERS_PK
  PRIMARY KEY
  (CUSTOMER_ID)
  USING INDEX OLIVER.DEMO_CUSTOMERS_PK
  ENABLE VALIDATE);

ALTER TABLE OLIVER.DEMO_CUSTOMERS ADD (
  CONSTRAINT DEMO_CUSTOMERS_UK
  UNIQUE (CUST_FIRST_NAME, CUST_LAST_NAME)
  USING INDEX OLIVER.DEMO_CUSTOMERS_UK
  ENABLE VALIDATE);

