-- 
-- Foreign Key Constraints for Table DEMO_ORDER_ITEMS 
-- 
ALTER TABLE OLIVER.DEMO_ORDER_ITEMS ADD (
  CONSTRAINT DEMO_ORDER_ITEMS_FK 
  FOREIGN KEY (ORDER_ID) 
  REFERENCES OLIVER.DEMO_ORDERS (ORDER_ID)
  ON DELETE CASCADE
  ENABLE VALIDATE);

ALTER TABLE OLIVER.DEMO_ORDER_ITEMS ADD (
  CONSTRAINT DEMO_ORDER_ITEMS_PRODUCT_ID_FK 
  FOREIGN KEY (PRODUCT_ID) 
  REFERENCES OLIVER.DEMO_PRODUCT_INFO (PRODUCT_ID)
  ON DELETE CASCADE
  ENABLE VALIDATE);

