-- 
-- Foreign Key Constraints for Table DEMO_ORDERS 
-- 
ALTER TABLE OLIVER.DEMO_ORDERS ADD (
  CONSTRAINT DEMO_ORDERS_CUSTOMER_ID_FK 
  FOREIGN KEY (CUSTOMER_ID) 
  REFERENCES OLIVER.DEMO_CUSTOMERS (CUSTOMER_ID)
  ON DELETE CASCADE
  ENABLE VALIDATE);

