-- 
-- Non Foreign Key Constraints for Table DEMO_PRODUCT_INFO 
-- 
ALTER TABLE OLIVER.DEMO_PRODUCT_INFO ADD (
  CONSTRAINT DEMO_PRODUCT_INFO_PK
  PRIMARY KEY
  (PRODUCT_ID)
  USING INDEX OLIVER.DEMO_PRODUCT_INFO_PK
  ENABLE VALIDATE);

ALTER TABLE OLIVER.DEMO_PRODUCT_INFO ADD (
  CONSTRAINT DEMO_PRODUCT_INFO_UK
  UNIQUE (PRODUCT_NAME)
  USING INDEX OLIVER.DEMO_PRODUCT_INFO_UK
  ENABLE VALIDATE);

