-- 
-- Non Foreign Key Constraints for Table DEMO_ORDER_ITEMS 
-- 
ALTER TABLE OLIVER.DEMO_ORDER_ITEMS ADD (
  CONSTRAINT DEMO_ORDER_ITEMS_PK
  PRIMARY KEY
  (ORDER_ITEM_ID)
  USING INDEX OLIVER.DEMO_ORDER_ITEMS_PK
  ENABLE VALIDATE);

ALTER TABLE OLIVER.DEMO_ORDER_ITEMS ADD (
  CONSTRAINT DEMO_ORDER_ITEMS_UK
  UNIQUE (ORDER_ID, PRODUCT_ID)
  USING INDEX OLIVER.DEMO_ORDER_ITEMS_UK
  ENABLE VALIDATE);

