-- 
-- Non Foreign Key Constraints for Table EBA_RESTDEMO_HTTP_HEADERS 
-- 
ALTER TABLE OLIVER.EBA_RESTDEMO_HTTP_HEADERS ADD (
  CONSTRAINT EBA_RESTDEMO_CK_HTTPHEAD_ACT
  CHECK ( header_active in ( 'Y', 'N' ) )
  ENABLE VALIDATE);

ALTER TABLE OLIVER.EBA_RESTDEMO_HTTP_HEADERS ADD (
  CONSTRAINT EBA_RESTDEMO_HTTPHEADERS_PK
  PRIMARY KEY
  (ID)
  USING INDEX OLIVER.EBA_RESTDEMO_HTTPHEADERS_PK
  ENABLE VALIDATE);

