-- 
-- Non Foreign Key Constraints for Table EBA_RESTDEMO_SERVICES 
-- 
ALTER TABLE OLIVER.EBA_RESTDEMO_SERVICES ADD (
  CONSTRAINT EBA_RESTDEMO_CK_ALLOWDEL
  CHECK ( data_allow_delete in ( 'Y', 'N' ) )
  ENABLE VALIDATE);

ALTER TABLE OLIVER.EBA_RESTDEMO_SERVICES ADD (
  CONSTRAINT EBA_RESTDEMO_CK_ALLOWINS
  CHECK ( data_allow_insert in ( 'Y', 'N' ) )
  ENABLE VALIDATE);

ALTER TABLE OLIVER.EBA_RESTDEMO_SERVICES ADD (
  CONSTRAINT EBA_RESTDEMO_CK_ALLOWUPD
  CHECK ( data_allow_update in ( 'Y', 'N' ) )
  ENABLE VALIDATE);

ALTER TABLE OLIVER.EBA_RESTDEMO_SERVICES ADD (
  CONSTRAINT EBA_RESTDEMO_CK_AUTHTYPE
  CHECK ( auth_type         in ( 'OAUTH2', 'BASIC', 'NONE' ) )
  ENABLE VALIDATE);

ALTER TABLE OLIVER.EBA_RESTDEMO_SERVICES ADD (
  CONSTRAINT EBA_RESTDEMO_CK_RESPONSETYPE
  CHECK ( response_type     in ( 'JSON', 'XML' ) )
  ENABLE VALIDATE);

ALTER TABLE OLIVER.EBA_RESTDEMO_SERVICES ADD (
  CONSTRAINT EBA_RESTDEMO_CK_SERVICETYPE
  CHECK ( service_type      in ( 'ORDS', 'HTTP' ) )
  ENABLE VALIDATE);

ALTER TABLE OLIVER.EBA_RESTDEMO_SERVICES ADD (
  CONSTRAINT EBA_RESTDEMO_SERVICES
  PRIMARY KEY
  (ID)
  USING INDEX OLIVER.EBA_RESTDEMO_SERVICES
  ENABLE VALIDATE);

