-- 
-- Non Foreign Key Constraints for Table EBA_DEMO_CHART_BBALL 
-- 
ALTER TABLE OLIVER.EBA_DEMO_CHART_BBALL ADD (
  CONSTRAINT EBA_DEMO_CHART_BBALL_PK
  PRIMARY KEY
  (ID)
  USING INDEX OLIVER.EBA_DEMO_CHART_BBALL_PK
  ENABLE VALIDATE);

