-- 
-- Non Foreign Key Constraints for Table EBA_DEMO_CHART_STOCKS 
-- 
ALTER TABLE OLIVER.EBA_DEMO_CHART_STOCKS ADD (
  CONSTRAINT EBA_DEMO_CHART_STOCKS_PK
  PRIMARY KEY
  (ID)
  USING INDEX OLIVER.EBA_DEMO_CHART_STOCKS_PK
  ENABLE VALIDATE);

