-- 
-- Non Foreign Key Constraints for Table EBA_RESTDEMO_LOG 
-- 
ALTER TABLE OLIVER.EBA_RESTDEMO_LOG ADD (
  CONSTRAINT EBA_RESTDEMO_LOG_PK
  PRIMARY KEY
  (ID)
  USING INDEX OLIVER.EBA_RESTDEMO_LOG_PK
  ENABLE VALIDATE);

