-- 
-- Non Foreign Key Constraints for Table EBA_DEMO_CHART_PRODUCTS 
-- 
ALTER TABLE OLIVER.EBA_DEMO_CHART_PRODUCTS ADD (
  CONSTRAINT EBA_DEMO_CHART_PROD_PK
  PRIMARY KEY
  (PRODUCT_ID)
  USING INDEX OLIVER.EBA_DEMO_CHART_PROD_PK
  ENABLE VALIDATE);

