-- 
-- Non Foreign Key Constraints for Table EBA_DEMO_CHART_ORDERS 
-- 
ALTER TABLE OLIVER.EBA_DEMO_CHART_ORDERS ADD (
  CONSTRAINT EBA_DEMO_CHART_ORDER_PK
  PRIMARY KEY
  (ORDER_ID)
  USING INDEX OLIVER.EBA_DEMO_CHART_ORDER_PK
  ENABLE VALIDATE);

