-- 
-- Non Foreign Key Constraints for Table EBA_DEMO_CHART_TASKS 
-- 
ALTER TABLE OLIVER.EBA_DEMO_CHART_TASKS ADD (
  CONSTRAINT EBA_DEMO_CHART_TASKS_PK
  PRIMARY KEY
  (ID)
  USING INDEX OLIVER.EBA_DEMO_CHART_TASKS_PK
  ENABLE VALIDATE);

