-- 
-- Foreign Key Constraints for Table EBA_DEMO_CHART_TASKS 
-- 
ALTER TABLE OLIVER.EBA_DEMO_CHART_TASKS ADD (
  CONSTRAINT EBA_DEMO_CHART_TASKS_FK 
  FOREIGN KEY (PROJECT) 
  REFERENCES OLIVER.EBA_DEMO_CHART_PROJECTS (ID)
  ON DELETE CASCADE
  ENABLE VALIDATE);

