-- 
-- Foreign Key Constraints for Table EBA_RESTDEMO_HTTP_HEADERS 
-- 
ALTER TABLE OLIVER.EBA_RESTDEMO_HTTP_HEADERS ADD (
  CONSTRAINT EBA_RESTDEMO_FK2_SERVICEID 
  FOREIGN KEY (SERVICE_ID) 
  REFERENCES OLIVER.EBA_RESTDEMO_SERVICES (ID)
  ON DELETE CASCADE
  ENABLE VALIDATE);

