-- 
-- Non Foreign Key Constraints for Table EBA_DEMO_CHART_PROJECTS 
-- 
ALTER TABLE OLIVER.EBA_DEMO_CHART_PROJECTS ADD (
  CONSTRAINT EBA_DEMO_CHARTS_PROJ_PK
  PRIMARY KEY
  (ID)
  USING INDEX OLIVER.EBA_DEMO_CHARTS_PROJ_PK
  ENABLE VALIDATE);

