-- 
-- Non Foreign Key Constraints for Table EBA_DEMO_CHART_EMP 
-- 
ALTER TABLE OLIVER.EBA_DEMO_CHART_EMP ADD (
  CONSTRAINT EBA_DEMO_CHART_EMP_PK
  PRIMARY KEY
  (EMPNO)
  USING INDEX OLIVER.EBA_DEMO_CHART_EMP_PK
  ENABLE VALIDATE);

