-- 
-- Foreign Key Constraints for Table EBA_DEMO_CHART_EMP 
-- 
ALTER TABLE OLIVER.EBA_DEMO_CHART_EMP ADD (
  FOREIGN KEY (MGR) 
  REFERENCES OLIVER.EBA_DEMO_CHART_EMP (EMPNO)
  ENABLE VALIDATE);

