-- 
-- Non Foreign Key Constraints for Table EBA_DEMO_CHART_DEPT 
-- 
ALTER TABLE OLIVER.EBA_DEMO_CHART_DEPT ADD (
  CONSTRAINT EBA_DEMO_CHART_DEPT_PK
  PRIMARY KEY
  (DEPTNO)
  USING INDEX OLIVER.EBA_DEMO_CHART_DEPT_PK
  ENABLE VALIDATE);

