-- 
-- Foreign Key Constraints for Table EBA_DEMO_CHART_ORDERS 
-- 
ALTER TABLE OLIVER.EBA_DEMO_CHART_ORDERS ADD (
  CONSTRAINT EBA_DEMO_CHART_ORDER_FK 
  FOREIGN KEY (PRODUCT_ID) 
  REFERENCES OLIVER.EBA_DEMO_CHART_PRODUCTS (PRODUCT_ID)
  ON DELETE CASCADE
  ENABLE VALIDATE);

