-- 
-- Non Foreign Key Constraints for Table EH_PLAN_BENEFIT 
-- 
ALTER TABLE OLIVER.EH_PLAN_BENEFIT ADD (
  CONSTRAINT EH_PLAN_BENEFIT_PK
  PRIMARY KEY
  (EPB_PLAN, EPB_BEN_CODE, EPB_EFF_DATE)
  USING INDEX OLIVER.EH_PLAN_BENEFIT_PK
  ENABLE VALIDATE);

