-- 
-- Non Foreign Key Constraints for Table EH_PLAN_BEN_TEMP 
-- 
ALTER TABLE OLIVER.EH_PLAN_BEN_TEMP ADD (
  CONSTRAINT PRIM1
  PRIMARY KEY
  (PLAN, BEN_CODE)
  USING INDEX OLIVER.PRIM1
  ENABLE VALIDATE);

