-- 
-- Foreign Key Constraints for Table EMP 
-- 
ALTER TABLE OLIVER.EMP ADD (
  FOREIGN KEY (DEPTNO) 
  REFERENCES OLIVER.DEPT (DEPTNO)
  ENABLE VALIDATE);

ALTER TABLE OLIVER.EMP ADD (
  FOREIGN KEY (MGR) 
  REFERENCES OLIVER.EMP (EMPNO)
  ENABLE VALIDATE);

