-- 
-- Foreign Key Constraints for Table SEC_ACCOUNT 
-- 
ALTER TABLE OLIVER.SEC_ACCOUNT ADD (
  CONSTRAINT FK_SEC_ACCOUNT_1 
  FOREIGN KEY (PROJECT_ID) 
  REFERENCES OLIVER.SEC_PROJECT (ID)
  ENABLE VALIDATE);

