-- 
-- Foreign Key Constraints for Table SEC_USER_GROUP_PROJECTS 
-- 
ALTER TABLE OLIVER.SEC_USER_GROUP_PROJECTS ADD (
  CONSTRAINT FK_SEC_USER_GROUP_PROJECTS_1 
  FOREIGN KEY (USER_GROUP_ID) 
  REFERENCES OLIVER.SEC_USER_GROUP (ID)
  ENABLE VALIDATE);

ALTER TABLE OLIVER.SEC_USER_GROUP_PROJECTS ADD (
  CONSTRAINT FK_SEC_USER_GROUP_PROJECTS_2 
  FOREIGN KEY (PROJECT_ID) 
  REFERENCES OLIVER.SEC_PROJECT (ID)
  ENABLE VALIDATE);

