-- 
-- Foreign Key Constraints for Table SEC_USER_GROUP_USERS 
-- 
ALTER TABLE OLIVER.SEC_USER_GROUP_USERS ADD (
  CONSTRAINT FK_SEC_USER_GROUP_USERS_1 
  FOREIGN KEY (USER_GROUP_ID) 
  REFERENCES OLIVER.SEC_USER_GROUP (ID)
  ENABLE VALIDATE);

ALTER TABLE OLIVER.SEC_USER_GROUP_USERS ADD (
  CONSTRAINT FK_SEC_USER_GROUP_USERS_2 
  FOREIGN KEY (USER_ID) 
  REFERENCES OLIVER.SEC_USER (ID)
  ENABLE VALIDATE);

