-- 
-- Non Foreign Key Constraints for Table TBL_EMPLOYER_FUND_RATES 
-- 
ALTER TABLE OLIVER.TBL_EMPLOYER_FUND_RATES ADD (
  CONSTRAINT TBL_EMPLOYER_FUND_RATES_PK
  PRIMARY KEY
  (PFR_CLIENT_ID, PFR_PLAN_ID, PFR_EMPLOYER, PFR_FUND_ID, PFR_EFF_DATE)
  USING INDEX OLIVER.TBL_EMPLOYER_FUND_RATES_PK
  ENABLE VALIDATE);

