-- 
-- Non Foreign Key Constraints for Table TBL_BENEFITS_MASTER 
-- 
ALTER TABLE OLIVER.TBL_BENEFITS_MASTER ADD (
  CONSTRAINT TBL_BENEFITS_MASTER_PK
  PRIMARY KEY
  (BM_CLIENT_ID, BM_PLAN, BM_EFF_DATE, BM_CODE)
  USING INDEX OLIVER.TBL_BENEFITS_MASTER_PK
  ENABLE VALIDATE);

