-- 
-- Non Foreign Key Constraints for Table TBL_BENEFITS_CLASS 
-- 
ALTER TABLE OLIVER.TBL_BENEFITS_CLASS ADD (
  CONSTRAINT UQ_BENEFITS_CLASS_KEY
  UNIQUE (BC_KEY)
  USING INDEX OLIVER.UQ_BENEFITS_CLASS_KEY
  ENABLE VALIDATE);

