-- 
-- Non Foreign Key Constraints for Table TBL_BENEFITS 
-- 
ALTER TABLE OLIVER.TBL_BENEFITS ADD (
  CONSTRAINT TBL_BENEFITS_PK
  PRIMARY KEY
  (BEN_PLAN, BEN_ID, BEN_EFF_DATE)
  USING INDEX OLIVER.TBL_BENEFITS_PK
  ENABLE VALIDATE);

