-- 
-- Non Foreign Key Constraints for Table TBL_ER_RATES 
-- 
ALTER TABLE OLIVER.TBL_ER_RATES ADD (
  CONSTRAINT TBL_ER_RATES_PK
  PRIMARY KEY
  (TER_CLIENT, TER_PLAN, TER_ID, TER_EFF_DATE)
  USING INDEX OLIVER.TBL_ER_RATES_PK
  ENABLE VALIDATE);

