-- 
-- Non Foreign Key Constraints for Table TBL_MEMBER 
-- 
ALTER TABLE OLIVER.TBL_MEMBER ADD (
  CONSTRAINT TBL_MEMBER_PK
  PRIMARY KEY
  (MEM_CLIENT_ID, MEM_PLAN, MEM_ID)
  USING INDEX OLIVER.TBL_MEMBER_PK
  ENABLE VALIDATE);

