-- 
-- Non Foreign Key Constraints for Table TBL_CLAIM_FILE 
-- 
ALTER TABLE OLIVER.TBL_CLAIM_FILE ADD (
  CONSTRAINT TBL_CLAIM_FILE_PK
  PRIMARY KEY
  (PLAN_ID, CLIENT_ID, MEM_ID, CLAIM_ID)
  USING INDEX OLIVER.TBL_CLAIM_FILE_PK
  ENABLE VALIDATE);

