-- 
-- Non Foreign Key Constraints for Table TBL_COMPHW 
-- 
ALTER TABLE OLIVER.TBL_COMPHW ADD (
  CONSTRAINT TBL_COMPHW_PK
  PRIMARY KEY
  (CH_PLAN, CH_NUMBER, CH_DIV, CH_CLIENT_ID)
  USING INDEX OLIVER.TBL_COMPHW_PK
  ENABLE VALIDATE);

