-- 
-- Non Foreign Key Constraints for Table TBL_MEMBER_NOTES 
-- 
ALTER TABLE OLIVER.TBL_MEMBER_NOTES ADD (
  CONSTRAINT MEMBER_NOTES_PK1
  PRIMARY KEY
  (MN_KEY)
  USING INDEX OLIVER.MEMBER_NOTES_PK1
  ENABLE VALIDATE);

