-- 
-- Non Foreign Key Constraints for Table TBL_PLAN_BANK 
-- 
ALTER TABLE OLIVER.TBL_PLAN_BANK ADD (
  CONSTRAINT TBL_PLAN_BANK_PK
  PRIMARY KEY
  (TPB_CLIENT, TPB_PLAN, TPB_PLAN_TYPE)
  USING INDEX OLIVER.TBL_PLAN_BANK_PK
  ENABLE VALIDATE);

