-- 
-- Non Foreign Key Constraints for Table TBL_MEMBER_T1 
-- 
ALTER TABLE OLIVER.TBL_MEMBER_T1 ADD (
  CONSTRAINT TBL_MEMBER_T1_PK
  PRIMARY KEY
  (MEM_CLIENT_ID, MEM_PLAN, MEM_ID)
  USING INDEX OLIVER.TBL_MEMBER_T1_INDEX1
  ENABLE VALIDATE);

