-- 
-- Non Foreign Key Constraints for Table TRANSACTION_DETAIL_TEMP 
-- 
ALTER TABLE OLIVER.TRANSACTION_DETAIL_TEMP ADD (
  CONSTRAINT DETAIL_TEMP_PK1
  PRIMARY KEY
  (TDT_KEY)
  USING INDEX OLIVER.DETAIL_TEMP_PK1
  ENABLE VALIDATE);

