-- 
-- Non Foreign Key Constraints for Table USERS 
-- 
ALTER TABLE OLIVER.USERS ADD (
  CONSTRAINT USERS_PK
  PRIMARY KEY
  (EMAIL, CLIENT_ID)
  USING INDEX OLIVER.USERS_PK
  ENABLE VALIDATE);

