--
-- AOP_OUTPUT  (Table) 
--
CREATE TABLE OLIVER.AOP_OUTPUT
(
  ID                NUMBER,
  OUTPUT_BLOB       BLOB,
  FILENAME          VARCHAR2(200 BYTE),
  MIME_TYPE         VARCHAR2(200 BYTE),
  LAST_UPDATE_DATE  DATE
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


