--
-- APEX_LOCKED_PAGES  (Table) 
--
CREATE TABLE OLIVER.APEX_LOCKED_PAGES
(
  LOCK_ID       NUMBER,
  LOCKED_BY     VARCHAR2(255 BYTE),
  LOCKED_ON     DATE,
  UNLOCKED_BY   VARCHAR2(255 BYTE),
  UNLOCKED_ON   DATE,
  APP_ID        NUMBER,
  PAGE_ID       NUMBER,
  LOCK_COMMENT  VARCHAR2(4000 BYTE),
  LOCK_BKP      CLOB,
  UNLOCK_BKP    CLOB
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


