--
-- APEX_APPLICATION_BACKUP  (Table) 
--
CREATE TABLE OLIVER.APEX_APPLICATION_BACKUP
(
  ID               NUMBER Generated as Identity ( START WITH 4737 MAXVALUE 9999999999999999999999999999 MINVALUE 1 NOCYCLE CACHE 20 NOORDER NOKEEP GLOBAL) NOT NULL,
  DESCRIPTION      VARCHAR2(255 BYTE),
  APP_ID           NUMBER,
  PAGE_ID          NUMBER,
  BACKUP_ON        DATE,
  APP_BACKUP       CLOB,
  APP_BACKUP_SIZE  VARCHAR2(255 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


