--
-- APP_PASSWORD_AUDIT  (Table) 
--
CREATE TABLE OLIVER.APP_PASSWORD_AUDIT
(
  ID            NUMBER Generated as Identity ( START WITH 142 MAXVALUE 9999999999999999999999999999 MINVALUE 1 NOCYCLE CACHE 20 NOORDER NOKEEP GLOBAL) NOT NULL,
  CLIENT_ID     VARCHAR2(2000 BYTE),
  CHANGED_USER  VARCHAR2(2000 BYTE),
  CHANGED_BY    VARCHAR2(2000 BYTE),
  AUDIT_DATE    DATE
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


