--
-- APP_ACCESS_AUDIT  (Table) 
--
CREATE TABLE OLIVER.APP_ACCESS_AUDIT
(
  ID                     NUMBER Generated as Identity ( START WITH 6980 MAXVALUE 9999999999999999999999999999 MINVALUE 1 NOCYCLE CACHE 20 NOORDER NOKEEP GLOBAL) NOT NULL,
  CLIENT_ID              VARCHAR2(2000 BYTE),
  USER_NAME              VARCHAR2(2000 BYTE),
  AUTH_RESULT            VARCHAR2(2000 BYTE),
  HTTP_HOST              VARCHAR2(2000 BYTE),
  HTTP_PORT              VARCHAR2(2000 BYTE),
  HTTP_REFERER           VARCHAR2(2000 BYTE),
  HTTP_USER_AGENT        VARCHAR2(2000 BYTE),
  PATH_INFO              VARCHAR2(2000 BYTE),
  REMOTE_ADDR            VARCHAR2(2000 BYTE),
  REMOTE_USER            VARCHAR2(2000 BYTE),
  REQUEST_METHOD         VARCHAR2(2000 BYTE),
  REQUEST_PROTOCOL       VARCHAR2(2000 BYTE),
  LOGIN_USERNAME_COOKIE  VARCHAR2(2000 BYTE),
  AUDIT_DATE             DATE,
  SESSION_ID             VARCHAR2(200 BYTE),
  LOGOUT_TIME            DATE
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


