--
-- APP_DEPLOYMENT_HISTORY  (Table) 
--
CREATE TABLE OLIVER.APP_DEPLOYMENT_HISTORY
(
  DEP_ID           NUMBER,
  PAGE_ID          NUMBER,
  PAGE_TITLE       VARCHAR2(100 BYTE),
  PAGE_GROUP       VARCHAR2(100 BYTE),
  VAR_NAME         VARCHAR2(100 BYTE),
  LAST_UPDATED_BY  VARCHAR2(100 BYTE),
  LAST_UPDATED_ON  DATE,
  NOTES            VARCHAR2(4000 BYTE),
  COL1             VARCHAR2(4000 BYTE),
  COL2             VARCHAR2(4000 BYTE),
  COL3             VARCHAR2(4000 BYTE),
  COL4             VARCHAR2(4000 BYTE),
  PAGE_TYPE        VARCHAR2(20 BYTE),
  APP_ID           NUMBER
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


