--
-- APP_USERS_AUDIT  (Table) 
--
CREATE TABLE OLIVER.APP_USERS_AUDIT
(
  ID             NUMBER Generated as Identity ( START WITH 1082 MAXVALUE 9999999999999999999999999999 MINVALUE 1 NOCYCLE CACHE 20 NOORDER NOKEEP GLOBAL) NOT NULL,
  EMAIL          VARCHAR2(2000 BYTE),
  AFFECTED_COLS  VARCHAR2(2000 BYTE),
  CREATED_BY     VARCHAR2(2000 BYTE),
  CREATED_ON     DATE,
  UPDATED_BY     VARCHAR2(2000 BYTE),
  UPDATED_ON     DATE,
  CLIENT_ID      VARCHAR2(2000 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


