--
-- AUDIT_TBL_MEM_BANK  (Table) 
--
CREATE TABLE OLIVER.AUDIT_TBL_MEM_BANK
(
  TMB_ID        VARCHAR2(100 BYTE),
  TMB_PL_ID     VARCHAR2(100 BYTE),
  TMB_BANK      VARCHAR2(100 BYTE),
  TMB_BRANCH    VARCHAR2(100 BYTE),
  TMB_ACCOUNT   VARCHAR2(100 BYTE),
  TMB_ACTIVE    VARCHAR2(1 BYTE),
  AUDIT_ACTION  CHAR(1 BYTE),
  AUDIT_BY      VARCHAR2(2000 BYTE),
  AUDIT_AT      TIMESTAMP(6)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


