--
-- AUDIT_APEX_ACCESS_LOG  (Table) 
--
CREATE TABLE OLIVER.AUDIT_APEX_ACCESS_LOG
(
  WORKSPACE                 VARCHAR2(255 BYTE)  NOT NULL,
  WORKSPACE_DISPLAY_NAME    VARCHAR2(4000 BYTE),
  APPLICATION_ID            NUMBER,
  APPLICATION_NAME          VARCHAR2(255 BYTE),
  USER_NAME                 VARCHAR2(255 BYTE),
  AUTHENTICATION_METHOD     VARCHAR2(255 BYTE),
  APPLICATION_SCHEMA_OWNER  VARCHAR2(255 BYTE),
  ACCESS_DATE               DATE,
  SECONDS_AGO               NUMBER,
  IP_ADDRESS                VARCHAR2(255 BYTE),
  AUTHENTICATION_RESULT     VARCHAR2(40 BYTE),
  CUSTOM_STATUS_TEXT        VARCHAR2(4000 BYTE),
  WORKSPACE_ID              NUMBER
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


