--
-- AUDIT_TBL_PENMAST  (Table) 
--
CREATE TABLE OLIVER.AUDIT_TBL_PENMAST
(
  PENM_ID                  VARCHAR2(100 BYTE)   NOT NULL,
  PENM_PLAN                VARCHAR2(10 BYTE)    NOT NULL,
  PENM_ENTRY_DATE          DATE,
  PENM_HIRE_DATE           DATE,
  PENM_STATUS              VARCHAR2(100 BYTE),
  PENM_STATUS_DATE         DATE,
  PENM_RECIPROCAL          VARCHAR2(1 BYTE),
  PENM_LOCAL               VARCHAR2(30 BYTE),
  PENM_EMPLOYER            VARCHAR2(100 BYTE),
  PENM_PAST_SERV           NUMBER(12,6),
  PENM_PAST_PENSION        NUMBER(12,2),
  PENM_CURR_SERV           NUMBER(12,6),
  PENM_CURR_PENSION        NUMBER(12,2),
  PENM_MARITAL_STATUS      VARCHAR2(100 BYTE),
  PENM_LRD                 DATE,
  PENM_VP_PENSION          NUMBER(12,2),
  PENM_PROCESS_DATE        DATE,
  PENM_CLIENT              VARCHAR2(20 BYTE)    NOT NULL,
  PENM_VETSED_DATE         DATE,
  PENM_PAST_PENSION_LI     NUMBER(12,2),
  PENM_LAST_MODIFIED_DATE  DATE,
  PENM_LAST_MODIFIED_BY    VARCHAR2(100 BYTE),
  AUDIT_ACTION             CHAR(1 BYTE),
  AUDIT_BY                 VARCHAR2(2000 BYTE),
  AUDIT_AT                 TIMESTAMP(6)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


