--
-- AUDIT_APEX_ACTIVITY_LOG  (Table) 
--
CREATE TABLE OLIVER.AUDIT_APEX_ACTIVITY_LOG
(
  WORKSPACE                 VARCHAR2(255 BYTE)  NOT NULL,
  WORKSPACE_DISPLAY_NAME    VARCHAR2(4000 BYTE),
  APEX_USER                 VARCHAR2(255 BYTE),
  APPLICATION_ID            NUMBER,
  APPLICATION_NAME          VARCHAR2(255 BYTE),
  APPLICATION_SCHEMA_OWNER  VARCHAR2(128 BYTE),
  PAGE_ID                   NUMBER,
  PAGE_NAME                 VARCHAR2(255 BYTE),
  VIEW_DATE                 DATE,
  THINK_TIME                NUMBER,
  SECONDS_AGO               NUMBER,
  LOG_CONTEXT               VARCHAR2(4000 BYTE),
  ELAPSED_TIME              NUMBER,
  ROWS_QUERIED              NUMBER,
  IP_ADDRESS                VARCHAR2(4000 BYTE),
  AGENT                     VARCHAR2(4000 BYTE),
  APEX_SESSION_ID           NUMBER,
  ERROR_MESSAGE             VARCHAR2(4000 BYTE),
  ERROR_ON_COMPONENT_TYPE   VARCHAR2(255 BYTE),
  ERROR_ON_COMPONENT_NAME   VARCHAR2(255 BYTE),
  PAGE_VIEW_MODE            VARCHAR2(15 BYTE),
  APPLICATION_INFO          VARCHAR2(4000 BYTE),
  INTERACTIVE_REPORT_ID     NUMBER,
  IR_SAVED_REPORT_ID        NUMBER,
  IR_SEARCH                 VARCHAR2(4000 BYTE),
  WS_APPLICATION_ID         NUMBER,
  WS_PAGE_ID                NUMBER,
  WS_DATAGRID_ID            NUMBER,
  CONTENT_LENGTH            NUMBER,
  REGIONS_FROM_CACHE        NUMBER,
  WORKSPACE_ID              NUMBER,
  PAGE_VIEW_TYPE            VARCHAR2(23 BYTE),
  REQUEST_VALUE             VARCHAR2(4000 BYTE),
  DEBUG_PAGE_VIEW_ID        NUMBER
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


