--
-- AUDIT_TBL_MEM_LOCAL_HIST  (Table) 
--
CREATE TABLE OLIVER.AUDIT_TBL_MEM_LOCAL_HIST
(
  ML_CLIENT        VARCHAR2(10 BYTE),
  ML_PLAN          VARCHAR2(10 BYTE),
  ML_ID            VARCHAR2(100 BYTE),
  ML_LOCAL         VARCHAR2(20 BYTE),
  ML_EFF_DATE      DATE,
  ML_TERM_DATE     DATE,
  ML_ENTERED_DATE  DATE,
  ML_RECIPROCAL    VARCHAR2(1 BYTE),
  ML_USR           VARCHAR2(100 BYTE),
  AUDIT_ACTION     CHAR(1 BYTE),
  AUDIT_BY         VARCHAR2(2000 BYTE),
  AUDIT_AT         TIMESTAMP(6)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


