--
-- AWS_BOT_TEST  (Table) 
--
CREATE TABLE OLIVER.AWS_BOT_TEST
(
  ID     VARCHAR2(100 BYTE),
  TOKEN  VARCHAR2(100 BYTE),
  EMAIL  VARCHAR2(100 BYTE)
)
TABLESPACE CDATV5DATAFILE
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


