--
-- BACKUP_TBL_CLAIM_COMMENTS  (Table) 
--
CREATE TABLE OLIVER.BACKUP_TBL_CLAIM_COMMENTS
(
  TCC_PLAN        VARCHAR2(10 BYTE),
  TCC_CLAIM       VARCHAR2(100 BYTE),
  TCC_SERVICE_ID  NUMBER,
  TCC_COMMENT     NUMBER
)
TABLESPACE CDATV5DATAFILE
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


