--
-- BCGEU_EMPLOYERS  (Table) 
--
CREATE TABLE OLIVER.BCGEU_EMPLOYERS
(
  CONTRACT_AREA      VARCHAR2(26 BYTE),
  CONTACT            VARCHAR2(26 BYTE),
  TITLE              VARCHAR2(128 BYTE),
  EMAIL              VARCHAR2(128 BYTE),
  COMPANY            VARCHAR2(128 BYTE),
  COMPNAY_ADDRESS_2  VARCHAR2(28 BYTE),
  COMPNAY_ADDRESS_3  VARCHAR2(25 BYTE),
  TELEPHONE          VARCHAR2(100 BYTE),
  FAX_NUMBER         VARCHAR2(100 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


