--
-- BENEFITS_VOLUME_BASED_310717  (Table) 
--
CREATE TABLE OLIVER.BENEFITS_VOLUME_BASED_310717
(
  BVB_BENEFIT         VARCHAR2(20 BYTE)         NOT NULL,
  BVB_VOLUME          NUMBER,
  BVB_NEM             NUMBER,
  BVB_MAX             NUMBER,
  BVB_RATE            NUMBER(12,6),
  BVB_AGENT           VARCHAR2(30 BYTE),
  BVB_ADMIN_RATE      NUMBER,
  BVB_EFFECTIVE_DATE  DATE                      NOT NULL,
  BVB_TERM_DATE       DATE,
  BVB_CLASS           VARCHAR2(10 BYTE)         NOT NULL,
  BVB_UNIT            NUMBER(12,2),
  BVB_CLIENT_ID       VARCHAR2(20 BYTE)         NOT NULL,
  BVB_PLAN_ID         VARCHAR2(20 BYTE)         NOT NULL
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


