--
-- BENEFITS_AGE_BASED_310717  (Table) 
--
CREATE TABLE OLIVER.BENEFITS_AGE_BASED_310717
(
  BAB_CLIENT_ID   VARCHAR2(20 BYTE)             NOT NULL,
  BAB_PLAN_ID     VARCHAR2(20 BYTE)             NOT NULL,
  BAB_BENEFIT     VARCHAR2(20 BYTE)             NOT NULL,
  BAB_CLASS       VARCHAR2(10 BYTE)             NOT NULL,
  BAB_EFF_DATE    DATE                          NOT NULL,
  BAB_TERM_DATE   DATE,
  BAB_SMOKER      VARCHAR2(1 BYTE)              NOT NULL,
  BAB_GENDER      VARCHAR2(1 BYTE)              NOT NULL,
  BAB_AGE         NUMBER(5,2)                   NOT NULL,
  BAB_RATE        NUMBER(12,6),
  BAB_ADMIN_RATE  NUMBER(12,6),
  BAB_AGENT       VARCHAR2(30 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


