--
-- BU_TBL_DOCUMENT  (Table) 
--
CREATE TABLE OLIVER.BU_TBL_DOCUMENT
(
  DOC_KEY         NUMBER(9),
  DOC_NAME        VARCHAR2(60 BYTE),
  DOC_DESC        VARCHAR2(500 BYTE),
  DOC_ATTACHMENT  BLOB,
  DOC_FILE_NAME   VARCHAR2(100 BYTE),
  DOC_MIME_TYPE   VARCHAR2(100 BYTE),
  DOC_PLAN        VARCHAR2(10 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


