--
-- CARRIER_FILE  (Table) 
--
CREATE TABLE OLIVER.CARRIER_FILE
(
  DATA_FILE       BLOB,
  PDF_FILE        BLOB,
  LAYOUT_VERSION  VARCHAR2(20 BYTE),
  DATE_ENTERED    DATE,
  DATA_FILE_NAME  VARCHAR2(100 BYTE),
  DATA_MIME_TYPE  VARCHAR2(100 BYTE),
  PDF_FILE_NAME   VARCHAR2(100 BYTE),
  PDF_MIME_TYPE   VARCHAR2(100 BYTE),
  CARRIER_ID      VARCHAR2(20 BYTE),
  CARRIER_KEY     NUMBER
)
TABLESPACE CDATV5DATAFILE
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


