--
-- CARRIER_HISTORY  (Table) 
--
CREATE TABLE OLIVER.CARRIER_HISTORY
(
  PLAN_ID            VARCHAR2(100 BYTE),
  CARRIER_ID         VARCHAR2(100 BYTE),
  CARRIER_SENT_DATE  DATE,
  SENT_BY            VARCHAR2(100 BYTE),
  TRANSACTION_ID     VARCHAR2(20 BYTE),
  STATUS             VARCHAR2(1 BYTE),
  CT_FILE_NAME       VARCHAR2(100 BYTE),
  CT_MIME_TYPE       VARCHAR2(100 BYTE),
  CT_FILE            BLOB
)
TABLESPACE CDATV5DATAFILE
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


