--
-- CARRIER_TEMP  (Table) 
--
CREATE TABLE OLIVER.CARRIER_TEMP
(
  CT_PLAN_ID         VARCHAR2(100 BYTE),
  CT_CARRIER_ID      VARCHAR2(100 BYTE),
  CT_MEM_ID          VARCHAR2(100 BYTE),
  CT_STATUS          VARCHAR2(1 BYTE),
  CT_KEY             NUMBER,
  CT_TRANSACTION_ID  VARCHAR2(20 BYTE)
)
TABLESPACE CDATV5DATAFILE
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


