--
-- COMPMAST_SUMA  (Table) 
--
CREATE TABLE OLIVER.COMPMAST_SUMA
(
  CO_NUMBER     VARCHAR2(20 BYTE),
  CO_DIV        VARCHAR2(2 BYTE),
  CO_NAME1      VARCHAR2(100 BYTE),
  CO_NAME2      VARCHAR2(30 BYTE),
  CO_ON_HW      CHAR(1 BYTE),
  CO_ON_PEN     CHAR(1 BYTE),
  CO_PLAN       VARCHAR2(1 BYTE),
  CO_POSTED     VARCHAR2(2 BYTE),
  CO_LAST_POST  DATE,
  CP_NAME1      VARCHAR2(100 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


