--
-- DB_RETIREES  (Table) 
--
CREATE TABLE OLIVER.DB_RETIREES
(
  PLANID            VARCHAR2(300 BYTE),
  PERSON_ID         VARCHAR2(300 BYTE),
  SIN               VARCHAR2(300 BYTE),
  TITLE             VARCHAR2(300 BYTE),
  LAST_NAME         VARCHAR2(300 BYTE),
  FIRST_NAME        VARCHAR2(300 BYTE),
  INITIAL1          VARCHAR2(300 BYTE),
  GENDER            VARCHAR2(300 BYTE),
  BIRTHDATE         VARCHAR2(300 BYTE),
  AGE               VARCHAR2(300 BYTE),
  HIREDATE          VARCHAR2(300 BYTE),
  MARITAL           VARCHAR2(300 BYTE),
  SPOUSE_ID         VARCHAR2(300 BYTE),
  SPOUSE_SIN        VARCHAR2(300 BYTE),
  SPOUSE_BIRTHDATE  VARCHAR2(300 BYTE),
  LANGUAGE          VARCHAR2(300 BYTE),
  ADDR1             VARCHAR2(300 BYTE),
  CITY              VARCHAR2(300 BYTE),
  PROV_STATE        VARCHAR2(300 BYTE),
  COUNTRY           VARCHAR2(300 BYTE),
  POSTALCODE        VARCHAR2(300 BYTE),
  PENSION_FORM      VARCHAR2(300 BYTE),
  TYPE1             VARCHAR2(300 BYTE),
  STARTDATE         VARCHAR2(300 BYTE),
  EXPIRYDATE        VARCHAR2(300 BYTE),
  SURVIVOR          VARCHAR2(300 BYTE),
  GUARANTEE         VARCHAR2(300 BYTE),
  SURVPERCNT        VARCHAR2(300 BYTE),
  PENSION           VARCHAR2(300 BYTE),
  BRIDGE            VARCHAR2(300 BYTE)
)
TABLESPACE CDATV5DATAFILE
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


