--
-- DEMO_CUSTOMERS  (Table) 
--
CREATE TABLE OLIVER.DEMO_CUSTOMERS
(
  CUSTOMER_ID           NUMBER                  NOT NULL,
  CUST_FIRST_NAME       VARCHAR2(20 BYTE)       NOT NULL,
  CUST_LAST_NAME        VARCHAR2(20 BYTE)       NOT NULL,
  CUST_STREET_ADDRESS1  VARCHAR2(60 BYTE),
  CUST_STREET_ADDRESS2  VARCHAR2(60 BYTE),
  CUST_CITY             VARCHAR2(30 BYTE),
  CUST_STATE            VARCHAR2(2 BYTE),
  CUST_POSTAL_CODE      VARCHAR2(10 BYTE),
  CUST_EMAIL            VARCHAR2(30 BYTE),
  PHONE_NUMBER1         VARCHAR2(25 BYTE),
  PHONE_NUMBER2         VARCHAR2(25 BYTE),
  URL                   VARCHAR2(100 BYTE),
  CREDIT_LIMIT          NUMBER(9,2),
  TAGS                  VARCHAR2(4000 BYTE)
)
TABLESPACE CDATV5DATAFILE
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


