--
-- DEMO_CONSTRAINT_LOOKUP  (Table) 
--
CREATE TABLE OLIVER.DEMO_CONSTRAINT_LOOKUP
(
  CONSTRAINT_NAME  VARCHAR2(30 BYTE),
  MESSAGE          VARCHAR2(4000 BYTE)          NOT NULL
)
TABLESPACE CDATV5DATAFILE
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


