--
-- DEMO_PRODUCT_INFO  (Table) 
--
CREATE TABLE OLIVER.DEMO_PRODUCT_INFO
(
  PRODUCT_ID           NUMBER                   NOT NULL,
  PRODUCT_NAME         VARCHAR2(50 BYTE),
  PRODUCT_DESCRIPTION  VARCHAR2(2000 BYTE),
  CATEGORY             VARCHAR2(30 BYTE),
  PRODUCT_AVAIL        VARCHAR2(1 BYTE),
  LIST_PRICE           NUMBER(8,2),
  PRODUCT_IMAGE        BLOB,
  MIMETYPE             VARCHAR2(255 BYTE),
  FILENAME             VARCHAR2(400 BYTE),
  IMAGE_LAST_UPDATE    TIMESTAMP(6) WITH LOCAL TIME ZONE,
  TAGS                 VARCHAR2(4000 BYTE)
)
TABLESPACE CDATV5DATAFILE
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


