--
-- DEMO_CLAIMS_HISTORY  (Table) 
--
CREATE TABLE OLIVER.DEMO_CLAIMS_HISTORY
(
  TYPE            VARCHAR2(255 BYTE),
  SIN             VARCHAR2(255 BYTE),
  LAST_NAME       VARCHAR2(255 BYTE),
  FIRST_NAME      VARCHAR2(255 BYTE),
  CLAIM#          VARCHAR2(255 BYTE),
  CLAIM_LINE      VARCHAR2(255 BYTE),
  CLAIM_STATUS    VARCHAR2(255 BYTE),
  SERVICE_DATE    VARCHAR2(255 BYTE),
  DEPENDENT#      VARCHAR2(255 BYTE),
  DEPENDENT_NAME  VARCHAR2(255 BYTE),
  SUBMITTED       NUMBER,
  LEVEL#          VARCHAR2(255 BYTE),
  DESCRIPTION     VARCHAR2(255 BYTE),
  CHEQUE_STATUS   VARCHAR2(255 BYTE),
  CHEQUE#         VARCHAR2(255 BYTE),
  ISSUED_DATE     VARCHAR2(255 BYTE),
  PAID            NUMBER,
  POLICY          VARCHAR2(255 BYTE),
  SUB_POLICY      VARCHAR2(255 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


