--
-- EBA_DEMO_CHART_PRODUCTS  (Table) 
--
CREATE TABLE OLIVER.EBA_DEMO_CHART_PRODUCTS
(
  PRODUCT_ID           NUMBER                   NOT NULL,
  PRODUCT_NAME         VARCHAR2(50 BYTE),
  PRODUCT_DESCRIPTION  VARCHAR2(2000 BYTE),
  LIST_PRICE           NUMBER(8,2),
  CREATED              TIMESTAMP(6) WITH LOCAL TIME ZONE,
  CREATED_BY           VARCHAR2(255 BYTE),
  UPDATED              TIMESTAMP(6) WITH LOCAL TIME ZONE,
  UPDATED_BY           VARCHAR2(255 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


