--
-- EBA_RESTDEMO_LOG  (Table) 
--
CREATE TABLE OLIVER.EBA_RESTDEMO_LOG
(
  ID               NUMBER,
  SERVICE_ID       NUMBER,
  SERVICE_NAME     VARCHAR2(200 BYTE),
  TIME_STAMP       TIMESTAMP(6) WITH LOCAL TIME ZONE NOT NULL,
  ACTION           VARCHAR2(100 BYTE),
  URL              VARCHAR2(4000 BYTE),
  RESPONSE_LENGTH  NUMBER,
  RESPONSE_STATUS  NUMBER,
  ELAPSED_TIME     NUMBER,
  ERROR_CODE       NUMBER,
  MESSAGE          VARCHAR2(4000 BYTE),
  USERNAME         VARCHAR2(255 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


