--
-- EH_COMMENT  (Table) 
--
CREATE TABLE OLIVER.EH_COMMENT
(
  COMM   NUMBER(3),
  DESC1  VARCHAR2(150 BYTE),
  DESC2  VARCHAR2(75 BYTE),
  CLAIM  VARCHAR2(8 BYTE)
)
TABLESPACE CDATV5DATAFILE
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


