--
-- JEFF_TRANSACTION_DETAIL_TEMP  (Table) 
--
CREATE TABLE OLIVER.JEFF_TRANSACTION_DETAIL_TEMP
(
  TDT_TRAN_ID      VARCHAR2(15 BYTE),
  TDT_EMPLOYER     VARCHAR2(100 BYTE),
  TDT_PLAN_ID      VARCHAR2(15 BYTE),
  TDT_START_DATE   DATE,
  TDT_END_DATE     DATE,
  TDT_PERIOD       DATE,
  TDT_UNITS        NUMBER(12,2),
  TDT_AMOUNT       NUMBER(12,2),
  TDT_COMMENT      VARCHAR2(3000 BYTE),
  TDT_USER         VARCHAR2(100 BYTE),
  TDT_DATE_TIME    DATE,
  TDT_MEM_ID       VARCHAR2(15 BYTE),
  TDT_KEY          NUMBER,
  TDT_LAST_NAME    VARCHAR2(60 BYTE),
  TDT_FIRST_NAME   VARCHAR2(60 BYTE),
  TDT_PEN_UNITS    NUMBER(12,2),
  TDT_FUNDS_UNITS  NUMBER(12,2),
  TDT_CLIENT_ID    VARCHAR2(20 BYTE),
  TDT_OCCU         VARCHAR2(100 BYTE),
  TDT_RATE         NUMBER(12,6)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


