--
-- OLIVER_DOCUMENTS_TMP  (Table) 
--
CREATE TABLE OLIVER.OLIVER_DOCUMENTS_TMP
(
  ID           NUMBER Generated as Identity ( START WITH 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 NOCYCLE CACHE 20 NOORDER NOKEEP GLOBAL) NOT NULL,
  FILE_NAME    VARCHAR2(255 BYTE),
  MIME_TYPE    VARCHAR2(60 BYTE),
  DESCRIPTION  VARCHAR2(60 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


