--
-- PORTAL_USERS_ACTIVITY  (Table) 
--
CREATE TABLE OLIVER.PORTAL_USERS_ACTIVITY
(
  EMAIL        VARCHAR2(100 BYTE),
  AUDIT_DATE   DATE,
  IPADDRESS    VARCHAR2(100 BYTE),
  AUTH_RESULT  VARCHAR2(20 BYTE),
  CLIENT_ID    VARCHAR2(20 BYTE),
  PLAN_ID      VARCHAR2(20 BYTE),
  FIRST_NAME   VARCHAR2(60 BYTE),
  LAST_NAME    VARCHAR2(60 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


