--
-- SUMA_MEMBER_BENEFIT_VW_290318  (Table) 
--
CREATE TABLE OLIVER.SUMA_MEMBER_BENEFIT_VW_290318
(
  COMPANY     VARCHAR2(20 BYTE),
  REAL_SIN    VARCHAR2(9 BYTE),
  SURNAME     VARCHAR2(30 BYTE),
  FIRST_NAME  VARCHAR2(25 BYTE),
  STATUS      VARCHAR2(10 BYTE),
  CLASS_STAT  VARCHAR2(1 BYTE),
  ID          VARCHAR2(9 BYTE),
  BEN_CODE    VARCHAR2(10 BYTE),
  BEN_DESC    VARCHAR2(100 BYTE),
  BEN_EFF     DATE,
  BEN_VOLUME  VARCHAR2(4000 BYTE),
  BILL        NUMBER,
  RATE        NUMBER,
  UNIT        NUMBER,
  EE_TYPE     VARCHAR2(2 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


