--
-- T938_UPLOAD  (Table) 
--
CREATE TABLE OLIVER.T938_UPLOAD
(
  ID        VARCHAR2(20 BYTE),
  SIN       NUMBER,
  DIVISION  NUMBER,
  LNAME     VARCHAR2(100 BYTE),
  FNAME     VARCHAR2(100 BYTE),
  STREET    VARCHAR2(200 BYTE),
  CITY      VARCHAR2(100 BYTE),
  PROV      VARCHAR2(20 BYTE),
  POSTAL    VARCHAR2(100 BYTE),
  DOB       VARCHAR2(100 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


