--
-- TBAS_TEMP_TEST  (Table) 
--
CREATE TABLE OLIVER.TBAS_TEMP_TEST
(
  TYPE           VARCHAR2(26 BYTE),
  SIN            VARCHAR2(26 BYTE),
  LAST_NMAE      VARCHAR2(100 BYTE),
  FIRST_NAME     VARCHAR2(100 BYTE),
  CLAIM          NUMBER(38,20),
  CLAIMLINE      NUMBER(38,20),
  CLAIMSTATUS    VARCHAR2(26 BYTE),
  SERVICEDATE    DATE,
  DEPENDENT      NUMBER(38,20),
  DEPENDANTNAME  VARCHAR2(100 BYTE),
  SUBMITTED      NUMBER(38,20),
  LEVEL1         NUMBER(38,20),
  DESCRIPTION    VARCHAR2(100 BYTE),
  CHEQUE_STATUS  VARCHAR2(26 BYTE),
  CHEQUE         NUMBER(38,6),
  ISSUED_DATE    NUMBER(20),
  PAID           NUMBER(38,20),
  POLICY         NUMBER(38,10),
  SUBPOLICY      NUMBER(38,10)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


