--
-- TBL_PLAN_BANK  (Table) 
--
CREATE TABLE OLIVER.TBL_PLAN_BANK
(
  TPB_CLIENT        VARCHAR2(20 BYTE)           NOT NULL,
  TPB_PLAN          VARCHAR2(20 BYTE)           NOT NULL,
  TPB_SUB_PLAN      VARCHAR2(20 BYTE),
  TPB_EFF_DATE      DATE,
  TPB_TRANSIT       NUMBER,
  TPB_BRANCH        NUMBER,
  TPB_ACCOUNT       NUMBER,
  TPB_PLAN_TYPE     VARCHAR2(100 BYTE)          NOT NULL,
  TPBP_CONTACT      VARCHAR2(100 BYTE),
  TPB_ADDRESS1      VARCHAR2(100 BYTE),
  TPB_ADDRESS2      VARCHAR2(100 BYTE),
  TPB_CITY          VARCHAR2(100 BYTE),
  TPB_PROV          VARCHAR2(100 BYTE),
  TPB_COUNTRY       VARCHAR2(100 BYTE)          DEFAULT 'CANADA',
  TPB_POSTAL_CODE   VARCHAR2(30 BYTE),
  TPB_PHONE1        VARCHAR2(100 BYTE),
  TPB_PHONE2        VARCHAR2(100 BYTE),
  TPB_FAX           VARCHAR2(100 BYTE),
  TPB_EMAIL1        VARCHAR2(100 BYTE),
  TPB_EMAIL2        VARCHAR2(100 BYTE),
  TPB_TERM_DATE     DATE,
  TPB_BANK          VARCHAR2(100 BYTE),
  TPB_ACCOUNT_NAME  VARCHAR2(100 BYTE)
)
TABLESPACE CDATV5DATAFILE
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


