--
-- TBL_PLAN_ACCOUNTS  (Table) 
--
CREATE TABLE OLIVER.TBL_PLAN_ACCOUNTS
(
  TPA_CLIENT        VARCHAR2(30 BYTE),
  TPA_PLAN          VARCHAR2(30 BYTE),
  TPA_ACCOUNT       VARCHAR2(10 BYTE),
  TPA_ACCOUNT_NAME  VARCHAR2(100 BYTE),
  TPA_EFF_DATE      DATE,
  TPA_TERM_DATE     DATE
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


