--
-- TBL_MEMBER_LOCATION  (Table) 
--
CREATE TABLE OLIVER.TBL_MEMBER_LOCATION
(
  MEM_CLIENT_ID    VARCHAR2(20 BYTE)            NOT NULL,
  MEM_PLAN         VARCHAR2(10 BYTE)            NOT NULL,
  MEM_ID           VARCHAR2(100 BYTE)           NOT NULL,
  MEM_FIRST_NAME   VARCHAR2(100 BYTE),
  MEM_LAST_NAME    VARCHAR2(100 BYTE),
  MEM_GENDER       VARCHAR2(1 BYTE),
  MEM_DOB          DATE,
  MEM_ADDRESS1     VARCHAR2(100 BYTE),
  MEM_CITY         VARCHAR2(100 BYTE),
  MEM_PROV         VARCHAR2(10 BYTE),
  MEM_COUNTRY      VARCHAR2(100 BYTE),
  MEM_POSTAL_CODE  VARCHAR2(20 BYTE),
  LAT              VARCHAR2(255 BYTE),
  LNG              VARCHAR2(255 BYTE),
  RSP              CLOB
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


