--
-- TBL_AGENT_EMPLOYERS  (Table) 
--
CREATE TABLE OLIVER.TBL_AGENT_EMPLOYERS
(
  AE_CLIENT_ID     VARCHAR2(30 BYTE),
  AE_PLAN_ID       VARCHAR2(30 BYTE),
  AE_AGENT_ID      NUMBER,
  AE_EMPLOYER      VARCHAR2(30 BYTE),
  AE_EFF_DATE      DATE,
  AE_TERM_DATE     DATE,
  AE_RATE          NUMBER(12,6)                 DEFAULT 0,
  AE_EMPLOYEES     NUMBER,
  AE_CREATED_DATE  DATE                         DEFAULT SYSDATE,
  AE_CREATED_BY    VARCHAR2(100 BYTE),
  AE_FINDER_FEE    NUMBER(12,6),
  AE_OTHER_FEE     NUMBER(12,6),
  AE_TRAILING_FEE  NUMBER,
  AE_TYPE          VARCHAR2(20 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


