--
-- TBL_OPTION_FACTORS_TEMP_JS60  (Table) 
--
CREATE TABLE OLIVER.TBL_OPTION_FACTORS_TEMP_JS60
(
  SPS_AGE  NUMBER(4),
  AGE55    NUMBER(9,6),
  AGE56    NUMBER(9,6),
  AGE57    NUMBER(9,6),
  AGE58    NUMBER(17,16),
  AGE59    NUMBER(9,6),
  AGE60    NUMBER(7,6),
  AGE61    NUMBER(7,6),
  AGE62    NUMBER(9,6),
  AGE63    NUMBER(7,6),
  AGE64    NUMBER(7,6),
  AGE65    NUMBER(9,6),
  AGE66    NUMBER(7,6),
  AGE67    NUMBER(7,6),
  AGE68    NUMBER(7,6),
  AGE69    NUMBER(7,6),
  AGE70    NUMBER(7,6),
  AGE71    NUMBER(7,6),
  AGE72    NUMBER(7,6)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


