--
-- TBL_AGREEMENT_TYPES  (Table) 
--
CREATE TABLE OLIVER.TBL_AGREEMENT_TYPES
(
  TAT_ID         NUMBER,
  TAT_CODE       VARCHAR2(20 BYTE),
  TAT_DESC       VARCHAR2(255 BYTE),
  TAT_PLAN_ID    VARCHAR2(20 BYTE),
  TAT_CLIENT_ID  VARCHAR2(20 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


