--
-- TBL_BENEFIC_RELATION  (Table) 
--
CREATE TABLE OLIVER.TBL_BENEFIC_RELATION
(
  TBR_CLIENT    VARCHAR2(30 BYTE),
  TBR_PLAN      VARCHAR2(30 BYTE),
  TBR_REL_CODE  VARCHAR2(255 BYTE),
  TBR_REL_DESC  VARCHAR2(255 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


