--
-- TBL_PLAN_RULES  (Table) 
--
CREATE TABLE OLIVER.TBL_PLAN_RULES
(
  TPR_CLIENT_ID            VARCHAR2(20 BYTE),
  TPR_PLAN_ID              VARCHAR2(20 BYTE),
  TPR_PROV                 VARCHAR2(10 BYTE),
  TPR_EFF_DATE             DATE,
  TPR_ELIG_MIN_MTHS        NUMBER,
  TPR_VEST_LOCKED_MTHS     NUMBER,
  TPR_VESTING_AT_NRD       DATE,
  TPR_MIN_ER_CONTS         NUMBER(12,2),
  TPR_EXCESS_EE_CONTS      NUMBER(12,2),
  TPR_MIN_EE_CONTS_INT     NUMBER(12,6),
  TPR_PORT_TERMI_EMPL      VARCHAR2(100 BYTE),
  TPR_NRD_AGE              NUMBER,
  TPR_ERD_AGE              NUMBER,
  TPR_POSTPONE_PEN_CREDIT  VARCHAR2(1 BYTE)     DEFAULT 'N',
  TPR_INTEGRATION_ALLOWED  VARCHAR2(1 BYTE)     DEFAULT 'N',
  TPR_INDEING_PERCENT      NUMBER(12,2)         DEFAULT 0,
  TPR_AIR_REQD             VARCHAR2(1 BYTE)     DEFAULT 'Y',
  TPR_AIR_MTHS             NUMBER,
  TPR_PEN_PERCENT          NUMBER(12,6)         DEFAULT 0,
  TPR_CV_PERCENT           NUMBER(12,6)         DEFAULT 0
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


