--
-- TBL_PENSION_ESTIMATOR  (Table) 
--
CREATE TABLE OLIVER.TBL_PENSION_ESTIMATOR
(
  TPE_CLIENT      VARCHAR2(20 BYTE),
  TPE_PLAN        VARCHAR2(20 BYTE),
  TPE_MEM_ID      VARCHAR2(30 BYTE),
  TPE_RET_DATE    DATE,
  TPE_YEAR        NUMBER(4),
  TPE_HRS         NUMBER(12,2)                  DEFAULT 0,
  TPE_EARNINGS    NUMBER(12,2)                  DEFAULT 0,
  TPE_EE_CONTS    NUMBER(12,2)                  DEFAULT 0,
  TPE_ER_CONTS    NUMBER(12,2)                  DEFAULT 0,
  TPE_PENSION     NUMBER(12,2)                  DEFAULT 0,
  TPE_CALC_DATE   DATE,
  TPE_CREATED_BY  VARCHAR2(100 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


