--
-- TBL_CLIENTS  (Table) 
--
CREATE TABLE OLIVER.TBL_CLIENTS
(
  CLIENT_ID           VARCHAR2(15 BYTE),
  CLIENT_NAME         VARCHAR2(50 BYTE),
  CLIENT_SU           VARCHAR2(50 BYTE),
  CLIENT_CONTACT      VARCHAR2(100 BYTE),
  CLIENT_ADDRESS      VARCHAR2(100 BYTE),
  CLIENT_CITY         VARCHAR2(30 BYTE),
  CLIENT_PROV         VARCHAR2(30 BYTE),
  CLIENT_POSTAL_CODE  VARCHAR2(10 BYTE),
  CLIENT_COUNTRY      VARCHAR2(20 BYTE),
  CLIENT_PHONE        VARCHAR2(20 BYTE),
  CLIENT_EMAIL        VARCHAR2(50 BYTE),
  CLIENT_EFF_DATE     DATE,
  CLIENT_TERM_DATE    DATE
)
TABLESPACE CDATV5DATAFILE
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


