--
-- TBL_PLAN_HR_BANK_CLASS_RATES_220318  (Table) 
--
CREATE TABLE OLIVER.TBL_PLAN_HR_BANK_CLASS_RATES_220318
(
  PHBCR_PLAN           VARCHAR2(10 BYTE)        NOT NULL,
  PHBCR_CLASS          VARCHAR2(100 BYTE),
  PHBCR_EFF_DATE       DATE                     NOT NULL,
  PHBCR_MIN_HRS        NUMBER(12,2),
  PHBCR_MAX_HRS        NUMBER(12,2),
  PHBCR_MONTHLY_HRS    NUMBER(12,2),
  PHBCR_SELF_PAY_MTHS  NUMBER,
  PH_FORFEIT_MTHS      NUMBER,
  PHCR_CLIENT_ID       VARCHAR2(20 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


