--
-- TBL_CLAIM_FILE  (Table) 
--
CREATE TABLE OLIVER.TBL_CLAIM_FILE
(
  PLAN_ID      VARCHAR2(12 BYTE),
  CLIENT_ID    VARCHAR2(12 BYTE),
  MEM_ID       VARCHAR2(12 BYTE),
  OUTPUT_BLOB  BLOB,
  FILENAME     VARCHAR2(200 BYTE),
  MIME_TYPE    VARCHAR2(200 BYTE),
  CREATE_DATE  DATE,
  CREATE_BY    VARCHAR2(100 BYTE),
  CLAIM_ID     VARCHAR2(20 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


