--
-- TBL_MEMBER_PORTAL_UPLOAD  (Table) 
--
CREATE TABLE OLIVER.TBL_MEMBER_PORTAL_UPLOAD
(
  ID            NUMBER,
  UPLOAD_NAME   VARCHAR2(100 BYTE),
  UPLOAD_FILE   BLOB,
  UPLOAD_DATE   DATE                            DEFAULT sysdate,
  UPLOAD_MIME   VARCHAR2(20 BYTE),
  MEMBER_ID     VARCHAR2(20 BYTE),
  PRACTITIONER  VARCHAR2(20 BYTE),
  SERVICE       VARCHAR2(255 BYTE),
  SERVICEDATE   DATE
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


