--
-- TBL_BENEFIT_LIMIT  (Table) 
--
CREATE TABLE OLIVER.TBL_BENEFIT_LIMIT
(
  TBL_CLIENT    VARCHAR2(20 BYTE),
  TBL_PLAN      VARCHAR2(20 BYTE),
  TBL_FFF_DATE  DATE,
  TBL_STATUS    VARCHAR2(10 BYTE),
  TBL_PERIOD    NUMBER,
  TBL_AMT       NUMBER(12,2)                    DEFAULT 0,
  TBL_BENEFIT   VARCHAR2(30 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


