--
-- TBL_FUNDS_CONTACT  (Table) 
--
CREATE TABLE OLIVER.TBL_FUNDS_CONTACT
(
  FUND_ID            NUMBER,
  FUND_ADDRESS1      VARCHAR2(100 BYTE),
  FUND_ADDRESS2      VARCHAR2(100 BYTE),
  FUND_CITY          VARCHAR2(100 BYTE),
  FUND_PROV          VARCHAR2(10 BYTE),
  FUND_POST_CODE     VARCHAR2(10 BYTE),
  FUND_COUNTRY       VARCHAR2(30 BYTE)          DEFAULT 'CANADA',
  FUND_EMAIL1        VARCHAR2(100 BYTE),
  FUND_EMAIL2        VARCHAR2(100 BYTE),
  FUND_PHONE1        VARCHAR2(100 BYTE),
  FUND_PHONE2        VARCHAR2(100 BYTE),
  FUND_FAX           VARCHAR2(100 BYTE),
  FUND_CONTACT_NAME  VARCHAR2(50 BYTE)
)
TABLESPACE CDATV5DATAFILE
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


