--
-- TBL_AGREEMENT_160118_2  (Table) 
--
CREATE TABLE OLIVER.TBL_AGREEMENT_160118_2
(
  TA_ID         VARCHAR2(20 BYTE),
  TA_DESC       VARCHAR2(1000 BYTE),
  TA_PLAN_ID    VARCHAR2(20 BYTE),
  TA_CLIENT_ID  VARCHAR2(20 BYTE),
  TA_EFF_DATE   DATE,
  TA_TERM_DATE  DATE
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


