--
-- TBL_PEN_EXIT_STATUSES  (Table) 
--
CREATE TABLE OLIVER.TBL_PEN_EXIT_STATUSES
(
  PES_ID       NUMBER,
  CODE         VARCHAR2(20 BYTE),
  DESCRIPTION  VARCHAR2(50 BYTE)
)
TABLESPACE CDATV5DATAFILE
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


