--
-- TBL_PLAN_PARAMETERS  (Table) 
--
CREATE TABLE OLIVER.TBL_PLAN_PARAMETERS
(
  TPP_CLIENT              VARCHAR2(20 BYTE),
  TPP_PLAN                VARCHAR2(20 BYTE),
  TPP_ER                  VARCHAR2(20 BYTE),
  TPP_EFF_DATE            DATE,
  TPP_UNITS               VARCHAR2(10 BYTE),
  TPP_AVG_MTHS            NUMBER(12,6),
  TPP_PLAN_TYPE           VARCHAR2(20 BYTE),
  TPP_VESTING_MTHS        NUMBER,
  TPP_SOLV_RATIO          NUMBER,
  TPP_SOLV_THRESHOLD      NUMBER,
  TPP_INDEXED             VARCHAR2(1 BYTE)      DEFAULT 'N',
  TPP_SUPP                VARCHAR2(1 BYTE)      DEFAULT 'N',
  TPP_BRIDGE              VARCHAR2(1 BYTE)      DEFAULT 'N',
  TPP_VP_A_UNITS          NUMBER(6,2),
  TPP_MAX_UNITS_ALLOWED   NUMBER(12,2),
  TPP_INHOUSE_PAYROLL     VARCHAR2(1 BYTE)      DEFAULT 'N',
  TPP_TRANSER_ALLOWED     VARCHAR2(1 BYTE)      DEFAULT 'N',
  TPP_TRANSFER_SERVICE    VARCHAR2(1 BYTE)      DEFAULT 'N',
  TPP_TRANSFER_PENSION    VARCHAR2(1 BYTE)      DEFAULT 'N',
  TPP_VARIANCE_THRESHOLD  NUMBER(12,2)          DEFAULT 0,
  TPP_ELIG_HRS            NUMBER(12,2),
  TPP_ELIG_MTHS           NUMBER,
  TPP_VEST_ELIG_YMPE      NUMBER(12,2),
  TPP_VESTING_HRS         NUMBER(12,2),
  TPP_VETST_CONSE_HRS     NUMBER(12,2),
  TPP_VEST_CONSE_MTHS     NUMBER(12,2),
  TPP_VEST_TOT_SERV       NUMBER,
  TPP_PARTICIP_HRS        NUMBER(12,2),
  TPP_TARGET_CONCERN      NUMBER,
  TPP_PLYEAR_START        DATE,
  TPP_PLYEAR_END          DATE
)
TABLESPACE CDATV5DATAFILE
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


