--
-- TBL_AGENTS  (Table) 
--
CREATE TABLE OLIVER.TBL_AGENTS
(
  AGENT_CLIENT_ID     VARCHAR2(30 BYTE),
  AGENT_PLAN_ID       VARCHAR2(30 BYTE),
  AGENT_ID            NUMBER,
  AGENT_FIRST_NAME    VARCHAR2(100 BYTE),
  AGENT_MIDDLE_NAME   VARCHAR2(100 BYTE),
  AGENT_LAST_NAME     VARCHAR2(100 BYTE),
  AGENT_ADDRESS1      VARCHAR2(100 BYTE),
  AGENT_ADDRESS2      VARCHAR2(100 BYTE),
  AGENT_CITY          VARCHAR2(100 BYTE),
  AGENT_PROV          VARCHAR2(10 BYTE),
  AGENT_COUNTRY       VARCHAR2(100 BYTE)        DEFAULT 'CANADA',
  AGENT_POSTAL_CODE   VARCHAR2(20 BYTE),
  AGENT_OFFICE_PHONE  VARCHAR2(30 BYTE),
  AGENT_MOBILE_PHONE  VARCHAR2(30 BYTE),
  AGENT_HOME_PHONE    VARCHAR2(30 BYTE),
  AGENT_EMAIL         VARCHAR2(100 BYTE),
  AGENT_FAX           VARCHAR2(100 BYTE),
  AGENT_CREATED       DATE                      DEFAULT SYSDATE,
  AGENT_CREATED_BY    VARCHAR2(100 BYTE),
  AGENT_EFF_DATE      DATE,
  AGENT_TERM_DATE     DATE,
  AGENT_TYPE          VARCHAR2(20 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


