--
-- TBL_HW_WAIVER_TYPES  (Table) 
--
CREATE TABLE OLIVER.TBL_HW_WAIVER_TYPES
(
  THWT_CLIENT     VARCHAR2(30 BYTE),
  THWT_PLAN       VARCHAR2(30 BYTE),
  THWT_CODE       VARCHAR2(20 BYTE),
  THWT_DESC       VARCHAR2(100 BYTE),
  THWT_EFF_DATE   DATE,
  THWT_TERM_DATE  DATE
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


