--
-- TBL_OPTION_FACTORS_LO_G  (Table) 
--
CREATE TABLE OLIVER.TBL_OPTION_FACTORS_LO_G
(
  OFLG_CLIENT        VARCHAR2(20 BYTE),
  OFLG_PLAN          VARCHAR2(20 BYTE),
  OFLG_TO_OPTION     VARCHAR2(30 BYTE),
  OFLG_AGE           NUMBER(12,6),
  OFLG_FACTOR        NUMBER(12,8)               DEFAULT 0,
  OFLG_EFF_DATE      DATE,
  OFLG_TERM_DATE     DATE,
  OFLG_CREATED_DATE  DATE                       DEFAULT SYSDATE,
  OFLG_CREATED_BY    VARCHAR2(100 BYTE),
  OFLG_FROM_OPTION   VARCHAR2(30 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


