--
-- TBL_TEMPORARY_FILES  (Table) 
--
CREATE GLOBAL TEMPORARY TABLE OLIVER.TBL_TEMPORARY_FILES
(
  ID           NUMBER Generated as Identity ( START WITH 66 MAXVALUE 9999999999999999999999999999 MINVALUE 1 NOCYCLE CACHE 20 NOORDER NOKEEP GLOBAL) NOT NULL,
  FILE_NAME    VARCHAR2(255 BYTE)               NOT NULL,
  FILE_BLOB    BLOB,
  FILE_CLOB    BLOB,
  FILE_LENGTH  NUMBER,
  MIME_TYPE    VARCHAR2(255 BYTE),
  CREATED_ON   DATE,
  CREATED_BY   VARCHAR2(255 BYTE)
)
ON COMMIT PRESERVE ROWS
RESULT_CACHE (MODE DEFAULT);


