--
-- TBL_MEM_SUSP_HIST  (Table) 
--
CREATE TABLE OLIVER.TBL_MEM_SUSP_HIST
(
  MSH_CLIENT        VARCHAR2(10 BYTE),
  MSH_PLAN          VARCHAR2(10 BYTE),
  MSH_ID            VARCHAR2(100 BYTE),
  MSH_LOCAL         VARCHAR2(20 BYTE),
  MSH_EFF_DATE      DATE,
  MSH_TERM_DATE     DATE,
  MSH_ENTERED_DATE  DATE,
  MSH_USR           VARCHAR2(100 BYTE)
)
TABLESPACE CDATV5DATAFILE
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


