--
-- TBL_CARRIER  (Table) 
--
CREATE TABLE OLIVER.TBL_CARRIER
(
  TC_CLIENT        VARCHAR2(30 BYTE),
  TC_PLAN          VARCHAR2(30 BYTE),
  TC_CARRIER_ID    VARCHAR2(20 BYTE),
  TC_CARRIER_NAME  VARCHAR2(100 BYTE),
  TC_EFF_DATE      DATE,
  TC_TERM_DATE     DATE,
  TC_ADDRESS1      VARCHAR2(100 BYTE),
  TC_ADDESS2       VARCHAR2(100 BYTE),
  TC_CITY          VARCHAR2(100 BYTE),
  TC_PROV          VARCHAR2(2 BYTE),
  TC_POSTAL_CODE   VARCHAR2(10 BYTE),
  TC_TELEPHONE1    VARCHAR2(30 BYTE),
  TC_TELEPHONE2    VARCHAR2(30 BYTE),
  TC_EMAIL         VARCHAR2(100 BYTE),
  TC_FAX           VARCHAR2(30 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


