--
-- TBL_EMPLOYER_CLASSES_190418  (Table) 
--
CREATE TABLE OLIVER.TBL_EMPLOYER_CLASSES_190418
(
  TEC_CLIENT_ID    VARCHAR2(20 BYTE),
  TEC_PLAN_ID      VARCHAR2(20 BYTE),
  TEC_ER_ID        VARCHAR2(30 BYTE),
  TEC_CLASS        VARCHAR2(100 BYTE),
  TEC_EFF_DATE     DATE,
  TEC_TERM_DATE    DATE,
  TEC_CREATE_DATE  DATE,
  TEC_CREATED_BY   VARCHAR2(100 BYTE),
  TEC_CLASS_KEY    NUMBER
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


