--
-- TBL_MEMBER_BENEFIT_ADJ  (Table) 
--
CREATE TABLE OLIVER.TBL_MEMBER_BENEFIT_ADJ
(
  BENEFIT_GROUP   VARCHAR2(30 BYTE),
  EMPLOYER        VARCHAR2(4000 BYTE),
  BM_BEN_TYPE     VARCHAR2(1 BYTE),
  CLIENT_ID       VARCHAR2(20 BYTE),
  PLAN_ID         VARCHAR2(20 BYTE),
  MEM_ID          VARCHAR2(100 BYTE)            NOT NULL,
  BEN_CLASS       VARCHAR2(100 BYTE),
  CODE            VARCHAR2(20 BYTE),
  BENDESC         VARCHAR2(1000 BYTE),
  COVERAGE        VARCHAR2(4000 BYTE),
  BEN_BILL        NUMBER,
  ADJ_EFF_DATE    DATE,
  ADJ_TERM_DATE   DATE,
  ADJ_RATE        NUMBER(12,6),
  ADJ_ADMIN_RATE  NUMBER(12,6),
  ADJ_AGENT_RATE  NUMBER(12,6),
  UNIT            NUMBER
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


