--
-- TBL_PEN_EXIT_STAT_TRANS  (Table) 
--
CREATE TABLE OLIVER.TBL_PEN_EXIT_STAT_TRANS
(
  PEST_ID            NUMBER,
  PEST_MEM_ID        VARCHAR2(20 BYTE),
  PEST_STATUS        VARCHAR2(20 BYTE),
  PEST_DATE_CREATED  DATE,
  PEST_PLAN          VARCHAR2(50 BYTE),
  PEST_CLIENT        VARCHAR2(50 BYTE),
  PEST_TYPE          VARCHAR2(20 BYTE)
)
TABLESPACE CDATV5DATAFILE
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


