--
-- TBL_PORTAL_GROUP  (Table) 
--
CREATE TABLE OLIVER.TBL_PORTAL_GROUP
(
  CLIENTID  VARCHAR2(20 BYTE),
  GROUPID   NUMBER,
  PORTALID  VARCHAR2(20 BYTE),
  PLANID    VARCHAR2(20 BYTE)
)
TABLESPACE CDATV5DATAFILE
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


