--
-- TBL_HSA_EXPENSES  (Table) 
--
CREATE TABLE OLIVER.TBL_HSA_EXPENSES
(
  ID            NUMBER,
  DESCRIPTION   VARCHAR2(255 BYTE),
  ISELIGIBLE    VARCHAR2(20 BYTE),
  SCRIPTNEEDED  VARCHAR2(20 BYTE),
  CERTNEEDED    VARCHAR2(20 BYTE),
  T2201NEEDED   VARCHAR2(20 BYTE),
  EXPLAIN       VARCHAR2(1000 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


