--
-- TBL_BENEFIT_RATES  (Table) 
--
CREATE TABLE OLIVER.TBL_BENEFIT_RATES
(
  TBR_ID        VARCHAR2(100 BYTE),
  TBR_PLAN      VARCHAR2(10 BYTE),
  TBR_CLIENT    VARCHAR2(20 BYTE),
  TBR_EFF_DATE  DATE,
  TBR_BEN_RATE  NUMBER(12,6)                    DEFAULT 0
)
TABLESPACE CDATV5DATAFILE
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


