--
-- TBL_OPTION_FACTORS_JS_TEST  (Table) 
--
CREATE TABLE OLIVER.TBL_OPTION_FACTORS_JS_TEST
(
  OFJS_CLIENT        VARCHAR2(20 BYTE),
  OFJS_PLAN          VARCHAR2(20 BYTE),
  OFJS_TO_OPTION     VARCHAR2(30 BYTE),
  OFJS_MEM_AGE       NUMBER(12,6),
  OFJS_SP_AGE        NUMBER(12,6),
  OFJS_FACTOR        NUMBER(12,8),
  OFJS_EFF_DATE      DATE,
  OFJS_TERM_DATE     DATE,
  OFJS_CREATED_DATE  DATE,
  OFJS_CREATED_BY    VARCHAR2(100 BYTE),
  OFJS_FROM_OPTION   VARCHAR2(30 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


