--
-- TBL_INVOICES  (Table) 
--
CREATE TABLE OLIVER.TBL_INVOICES
(
  TI_CLIENT_ID     VARCHAR2(20 BYTE),
  TI_PLAN_ID       VARCHAR2(20 BYTE),
  TE_ER_ID         VARCHAR2(30 BYTE),
  TI_EE_ID         VARCHAR2(20 BYTE),
  TI_INVOICE_NUM   VARCHAR2(100 BYTE),
  TI_DESC          VARCHAR2(3000 BYTE),
  TI_MTH           DATE,
  TI_BENEFIT       VARCHAR2(30 BYTE),
  TI_BILL_AMT      NUMBER(12,2),
  TI_PAYMENT       NUMBER(12,2),
  TI_PAYMENT_NUM   VARCHAR2(100 BYTE),
  TI_ADMIN         NUMBER(12,2),
  TI_AGENT         NUMBER(12,2),
  TI_MISC          NUMBER(12,2),
  TI_ADJ           NUMBER(12,2),
  TI_COMMENT       VARCHAR2(3000 BYTE),
  TI_CREATED_BY    VARCHAR2(100 BYTE),
  TI_CREATED_DATE  DATE
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


