--
-- TBL_HW_220318  (Table) 
--
CREATE TABLE OLIVER.TBL_HW_220318
(
  HW_PLAN                 VARCHAR2(10 BYTE)     NOT NULL,
  HW_ID                   VARCHAR2(100 BYTE)    NOT NULL,
  HW_EFF_DATE             DATE,
  HW_TERM_DATE            DATE,
  HW_COVERAGE             VARCHAR2(100 BYTE),
  HW_EMPLOYER             VARCHAR2(100 BYTE),
  HW_DIV                  VARCHAR2(10 BYTE),
  HW_BILLING_CODE         NUMBER,
  HW_TERM_CODE            NUMBER,
  HW_APP_RECD             VARCHAR2(1 BYTE),
  HW_LAST_MODIFIED_DATE   DATE,
  HW_LAST_MODIFIED_BY     VARCHAR2(100 BYTE),
  HW_LOCAL                VARCHAR2(20 BYTE),
  HW_LOCAL_EFF_DATE       DATE,
  HW_RECIPROCAL           VARCHAR2(1 BYTE),
  HW_RECIPROCAL_DATE      DATE,
  HW_SUSPENED             VARCHAR2(1 BYTE),
  HW_SUSP_DATE            DATE,
  HW_SUSP_REASON          VARCHAR2(3000 BYTE),
  HW_CLASS                VARCHAR2(10 BYTE),
  HW_STATUS               VARCHAR2(10 BYTE),
  HW_MEM_CATEGORY         VARCHAR2(1 BYTE),
  HW_SUB_PLAN             VARCHAR2(10 BYTE),
  HW_SUBSIDIZED           VARCHAR2(1 BYTE),
  HW_LATE_APP             VARCHAR2(1 BYTE),
  HW_LATE_EFF_DATE        DATE,
  HW_LATE_TERM_DATE       DATE,
  HW_CLIENT               VARCHAR2(20 BYTE),
  HW_SMOKER               VARCHAR2(1 BYTE),
  HW_EE_TYPE              VARCHAR2(10 BYTE),
  HW_COUPLE_DEP_NO        NUMBER,
  HW_VISION_ELIGIBLE      VARCHAR2(1 BYTE),
  HW_SPOUSAL_SMOKER       VARCHAR2(1 BYTE),
  HW_DEP_STATUS           VARCHAR2(1 BYTE),
  HW_SMOKER_EFF_DATE      DATE,
  HW_SP_SMOKER_EFF_DATE   DATE,
  HW_DEP_STATUS_EFF_DATE  DATE,
  HW_CLASS_EFF_DATE       DATE
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


