--
-- TBL_ER_RATES_HW  (Table) 
--
CREATE TABLE OLIVER.TBL_ER_RATES_HW
(
  TER_ID        VARCHAR2(100 BYTE),
  TER_PLAN      VARCHAR2(10 BYTE),
  TER_EFF_DATE  DATE,
  TER_RATE      NUMBER(12,6),
  TER_EE_RATE   NUMBER(12,6),
  TER_HW_RATE   NUMBER(12,6),
  TER_CLIENT    VARCHAR2(20 BYTE)
)
TABLESPACE CDATV5DATAFILE
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


