--
-- TBL_PENSION_FORMS  (Table) 
--
CREATE TABLE OLIVER.TBL_PENSION_FORMS
(
  ID                VARCHAR2(20 BYTE),
  DESCRIPTION       VARCHAR2(255 BYTE),
  TPF_CLIENT        VARCHAR2(20 BYTE),
  TPF_PLAN          VARCHAR2(20 BYTE),
  TPF_EFF_DATE      DATE,
  TPF_TERM_DATE     DATE,
  TPF_CREATED_DATE  DATE,
  TPF_CREATED_BY    VARCHAR2(100 BYTE),
  OLIVER_TEMP_FORM  VARCHAR2(20 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


