--
-- "TBL_RETIREES_bcgeu"  (Table) 
--
CREATE TABLE OLIVER."TBL_RETIREES_bcgeu"
(
  RET_MEM_ID         VARCHAR2(30 BYTE),
  RET_CLIENT_ID      VARCHAR2(20 BYTE),
  RET_PLAN_ID        VARCHAR2(20 BYTE),
  RET_RETIRE_DATE    DATE,
  RET_PEN_OPTION     VARCHAR2(100 BYTE),
  RET_PEN_TYPE       VARCHAR2(10 BYTE),
  RET_PEN_AMT        NUMBER(12,2)               DEFAULT 0,
  RET_BRIDGE_AMT     NUMBER(12,2)               DEFAULT 0,
  RET_GTEE_MTHS      NUMBER(6,2),
  RET_SURVIVOR_PER   NUMBER(5,2),
  RET_SURVIVOR_SIN   NUMBER,
  RET_END_GTEE_DATE  DATE,
  RET_SUPP1_AMT      NUMBER(12,2),
  RET_SUPP2_AMT      NUMBER(12,2),
  RET_RED_AMT        NUMBER(12,2),
  RET_TAX_CODE       VARCHAR2(10 BYTE),
  RET_CREATED_DATE   DATE,
  RET_CREATED_BY     VARCHAR2(100 BYTE),
  RET_MODIFIED_DATE  DATE,
  RET_MODIFIED_BY    VARCHAR2(100 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


