--
-- TBL_MARITAL_STATUS  (Table) 
--
CREATE TABLE OLIVER.TBL_MARITAL_STATUS
(
  TMS_CLIENT             VARCHAR2(20 BYTE),
  TMS_PLAN               VARCHAR2(20 BYTE),
  TMS_MEM_ID             VARCHAR2(100 BYTE),
  TMS_EFF_DATE           DATE,
  TMS_TERM_DATE          DATE,
  TMS_BENEFIT            VARCHAR2(20 BYTE),
  TMS_STATUS             VARCHAR2(10 BYTE),
  TMS_CREATED_BY         VARCHAR2(100 BYTE),
  TMS_CREATED_DATE       DATE,
  TMS_KEY                NUMBER,
  TMS_LAST_UPDATED_BY    VARCHAR2(100 BYTE),
  TMS_LAST_UPDATED_DATE  DATE
)
TABLESPACE CDATV5DATAFILE
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


