--
-- TBL_BEN_REDUCTION  (Table) 
--
CREATE TABLE OLIVER.TBL_BEN_REDUCTION
(
  TBR_CLIENT_ID  VARCHAR2(20 BYTE),
  TBR_PLAN_ID    VARCHAR2(20 BYTE),
  TBR_EFF_DATE   DATE,
  TBR_BEN_CODE   VARCHAR2(20 BYTE),
  TBR_AGE        NUMBER(12,6),
  TBR_RED        NUMBER(12,6)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


