--
-- TBL_BENEFIT_COVERAGE_STATUS  (Table) 
--
CREATE TABLE OLIVER.TBL_BENEFIT_COVERAGE_STATUS
(
  BDS_PL_ID          VARCHAR2(20 BYTE),
  BDS_MEM_ID         VARCHAR2(20 BYTE),
  BDS_BENEFIT        VARCHAR2(6 BYTE),
  BDS_COVERAGE       VARCHAR2(1 BYTE),
  BDS_EFF_DATE       DATE,
  BDS_TERM_DATE      DATE,
  BDS_CLIENT_ID      VARCHAR2(20 BYTE),
  BDS_COUPLE_DEP_NO  NUMBER
)
TABLESPACE CDATV5DATAFILE
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


