--
-- TBL_MEM_BANK  (Table) 
--
CREATE TABLE OLIVER.TBL_MEM_BANK
(
  TMB_ID       VARCHAR2(100 BYTE),
  TMB_PL_ID    VARCHAR2(100 BYTE),
  TMB_BANK     VARCHAR2(100 BYTE),
  TMB_BRANCH   VARCHAR2(100 BYTE),
  TMB_ACCOUNT  VARCHAR2(100 BYTE),
  TMB_ACTIVE   VARCHAR2(1 BYTE)                 DEFAULT 'Y'
)
TABLESPACE CDATV5DATAFILE
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


