--
-- TBLCONTRIBS_PATCH  (Table) 
--
CREATE TABLE OLIVER.TBLCONTRIBS_PATCH
(
  PLANID        VARCHAR2(26 BYTE),
  SIGNATURE     NUMBER(26,6),
  SEMAPHORE     NUMBER(26,6),
  BATCH_ID      VARCHAR2(26 BYTE),
  PERSON_ID     VARCHAR2(26 BYTE),
  ORGANS_ID     VARCHAR2(26 BYTE),
  ENTRYDATE     DATE,
  EFFECTDATE    DATE,
  TRANSTYPE     VARCHAR2(26 BYTE),
  TRANSTYPE_UC  NUMBER(26,6),
  UNITS         NUMBER(38,18),
  UNITS_TYPE    VARCHAR2(26 BYTE),
  RATE          NUMBER(38,18),
  AMOUNT        NUMBER(38,18),
  COMMENTS      VARCHAR2(300 BYTE),
  UNITS_ORIG    NUMBER(26,6),
  LOCAL         VARCHAR2(26 BYTE),
  RATE_CLASS    VARCHAR2(26 BYTE),
  FDIS_ID       NUMBER(26,6)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


