--
-- TEMP_CLAIM_MEMBER  (Table) 
--
CREATE TABLE OLIVER.TEMP_CLAIM_MEMBER
(
  MEMBER_OR_DEP    NUMBER(2),
  REAL_SIN         VARCHAR2(12 BYTE),
  SURNAME          VARCHAR2(50 BYTE),
  FIRST_NAME       VARCHAR2(50 BYTE),
  ADDRESS1         VARCHAR2(100 BYTE),
  CITY             VARCHAR2(50 BYTE),
  PROV             VARCHAR2(30 BYTE),
  POST_CODE        VARCHAR2(30 BYTE),
  SEX              VARCHAR2(1 BYTE),
  BIRTH_DATE       DATE,
  COMPANY          VARCHAR2(12 BYTE),
  LATE_APPLICANT   VARCHAR2(1 BYTE),
  VISION_DATE      DATE,
  VISION           VARCHAR2(12 BYTE),
  DEP_EFFECT_DATE  DATE
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


