--
-- TEMP_TRANSACTION_POST  (Table) 
--
CREATE TABLE OLIVER.TEMP_TRANSACTION_POST
(
  PLAN_ID        VARCHAR2(15 BYTE),
  CLIENT_ID      VARCHAR2(15 BYTE),
  TRANS_ID       VARCHAR2(15 BYTE),
  EMPLOYER_ID    VARCHAR2(15 BYTE),
  EMPLOYER_NAME  VARCHAR2(100 BYTE),
  BY_USER        VARCHAR2(50 BYTE),
  BENEFIT        VARCHAR2(1 BYTE),
  PENSION        VARCHAR2(1 BYTE),
  FUND           VARCHAR2(1 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


