--
-- TMP_TRANSLATE  (Table) 
--
CREATE TABLE OLIVER.TMP_TRANSLATE
(
  CLIENT_ID    VARCHAR2(20 BYTE),
  PLAN_ID      VARCHAR2(20 BYTE),
  GLOBAL_TERM  VARCHAR2(100 BYTE),
  CLIENT_TERM  VARCHAR2(100 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


