--
-- TMP_TBL_REPORT  (Table) 
--
CREATE GLOBAL TEMPORARY TABLE OLIVER.TMP_TBL_REPORT
(
  CARD_SUBTEXT   VARCHAR2(100 BYTE),
  CARD_INITIALS  VARCHAR2(8 BYTE),
  CARD_TITLE     VARCHAR2(100 BYTE),
  CARD_TEXT      VARCHAR2(255 BYTE),
  CARD_ICON      VARCHAR2(13 BYTE),
  CARD_LINK      VARCHAR2(4000 BYTE)
)
ON COMMIT PRESERVE ROWS
RESULT_CACHE (MODE DEFAULT);


