--
-- TMP_DATAENTRY  (Table) 
--
CREATE TABLE OLIVER.TMP_DATAENTRY
(
  EMAIL        VARCHAR2(100 BYTE),
  FNAME        VARCHAR2(20 BYTE),
  LANME        VARCHAR2(20 BYTE),
  DOB          DATE,
  PHONE        VARCHAR2(20 BYTE),
  MEMID        NUMBER,
  SIN          NUMBER,
  BENEFICIARY  VARCHAR2(100 BYTE),
  SIGNATURE    BLOB
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


