--
-- TMP_TESTING_IG  (Table) 
--
CREATE TABLE OLIVER.TMP_TESTING_IG
(
  ID             VARCHAR2(20 BYTE),
  BEN_CODE       VARCHAR2(20 BYTE),
  SERVICEDATE    VARCHAR2(20 BYTE),
  AMOUNTCLAIMED  VARCHAR2(20 BYTE),
  OTHER          VARCHAR2(20 BYTE),
  COMMENTS       VARCHAR2(20 BYTE)
)
TABLESPACE CDATV5DATAFILE
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


