--
-- TMP_TBL_REPORT1  (Table) 
--
CREATE GLOBAL TEMPORARY TABLE OLIVER.TMP_TBL_REPORT1
(
  REPORT_ID    NUMBER                           NOT NULL,
  PLAN_ID      VARCHAR2(10 BYTE),
  CATEGORY     VARCHAR2(100 BYTE),
  REPORT_NAME  VARCHAR2(100 BYTE),
  DESCRIPTION  VARCHAR2(255 BYTE),
  PAGE_ID      INTEGER,
  ISACTIVE     VARCHAR2(1 BYTE),
  TAGS         VARCHAR2(2000 BYTE)
)
ON COMMIT PRESERVE ROWS
RESULT_CACHE (MODE DEFAULT);


