--
-- TRAN_HEADDER_TEMP_FUNDS_DET  (Table) 
--
CREATE TABLE OLIVER.TRAN_HEADDER_TEMP_FUNDS_DET
(
  HTFD_TRAN_ID     VARCHAR2(15 BYTE),
  HTFD_FUND        VARCHAR2(1000 BYTE),
  HTFD_UNITS       NUMBER(12,2)                 DEFAULT 0,
  HTFD_RATE        NUMBER(12,5)                 DEFAULT 0,
  HTFD_AMT         NUMBER(12,2)                 DEFAULT 0,
  THTFD_CLIENT_ID  VARCHAR2(20 BYTE),
  HTFD_AGREE_ID    VARCHAR2(100 BYTE)
)
TABLESPACE CDATV5DATAFILE
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


