--
-- TRANSACTION_HEADER_FUNDS  (Table) 
--
CREATE TABLE OLIVER.TRANSACTION_HEADER_FUNDS
(
  THF_EMPLOYER           VARCHAR2(100 BYTE),
  THF_PLAN_ID            VARCHAR2(15 BYTE),
  THF_START_DATE         DATE,
  THF_END_DATE           DATE,
  THF_PERIOD             DATE,
  THF_UNITS              NUMBER(12,2)           DEFAULT 0,
  THF_RATE               NUMBER(12,5)           DEFAULT 0,
  THF_AMOUNT             NUMBER(12,2)           DEFAULT 0,
  THF_PAYMENT_TYPE       VARCHAR2(10 BYTE),
  THF_COMMENT            VARCHAR2(3000 BYTE),
  THF_USER               VARCHAR2(100 BYTE),
  THF_DATE_TIME          DATE,
  THF_MEM_ID             VARCHAR2(15 BYTE),
  THF_TRAN_ID            VARCHAR2(15 BYTE),
  THF_POSTED_DATE        DATE,
  THF_POSTED_USER        VARCHAR2(100 BYTE),
  THF_CHEQUE             VARCHAR2(20 BYTE),
  THF_UNITS_EARNED       NUMBER(12,2)           DEFAULT 0,
  THF_RECD_AMT           NUMBER(12,2)           DEFAULT 0,
  THF_VARIANCE_AMT       NUMBER(12,2)           DEFAULT 0,
  THF_VAR_REASON         VARCHAR2(1000 BYTE),
  THF_DEPOSIT_NUMBER     VARCHAR2(1000 BYTE),
  THF_CLIENT_ID          VARCHAR2(20 BYTE),
  THF_AGREE_ID           VARCHAR2(20 BYTE),
  THF_DEPOSIT_SLIP_DATE  DATE,
  THF_WRITE_OFF_AMT      NUMBER,
  THF_TRAN_LABEL         VARCHAR2(100 BYTE)
)
TABLESPACE CDATV5DATAFILE
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


