--
-- TRANSACTION_HEADER_TEMP  (Table) 
--
CREATE TABLE OLIVER.TRANSACTION_HEADER_TEMP
(
  THT_EMPLOYER           VARCHAR2(100 BYTE)     NOT NULL,
  THT_PLAN_ID            VARCHAR2(15 BYTE),
  THT_START_DATE         DATE,
  THT_END_DATE           DATE,
  THT_PERIOD             DATE,
  THT_UNITS              NUMBER(12,2)           DEFAULT 0,
  THT_RATE               NUMBER(12,5)           DEFAULT 0,
  THT_AMOUNT             NUMBER(12,2)           DEFAULT 0,
  THT_PAYMENT_TYPE       VARCHAR2(10 BYTE),
  THT_COMMENT            VARCHAR2(3000 BYTE),
  THT_USER               VARCHAR2(100 BYTE),
  THT_DATE_TIME          DATE,
  THT_MEM_ID             VARCHAR2(15 BYTE),
  THT_TRAN_ID            VARCHAR2(15 BYTE),
  THT_POST               VARCHAR2(1 BYTE)       DEFAULT 'N',
  THT_CHEQUE             VARCHAR2(20 BYTE),
  THT_POSTED_DATE        DATE,
  THT_EARNED             VARCHAR2(1 BYTE)       DEFAULT 'N',
  THT_RECD_AMT           NUMBER(12,2)           DEFAULT 0,
  THT_VARIANCE_AMT       NUMBER(12,2)           DEFAULT 0,
  THT_VAR_REASON         VARCHAR2(1000 BYTE),
  THT_CLIENT_ID          VARCHAR2(20 BYTE),
  THT_DEPOSIT_NUMBER     VARCHAR2(1000 BYTE),
  THT_AGREE_ID           VARCHAR2(20 BYTE),
  THT_EE_UNITS           NUMBER(12,2),
  THT_ER_UNITS           NUMBER(12,2),
  THT_EE_ACCOUNT         VARCHAR2(10 BYTE),
  THT_ER_ACCOUNT         VARCHAR2(10 BYTE),
  THT_DEPOSIT_SLIP_DATE  DATE,
  THT_WRITE_OFF_AMT      NUMBER,
  THT_TRAN_LABEL         VARCHAR2(100 BYTE)
)
TABLESPACE CDATV5DATAFILE
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


