--
-- TRANSACTION_HEADER_PEN  (Table) 
--
CREATE TABLE OLIVER.TRANSACTION_HEADER_PEN
(
  THP_EMPLOYER           VARCHAR2(100 BYTE),
  THP_PLAN_ID            VARCHAR2(15 BYTE),
  THP_START_DATE         DATE,
  THP_END_DATE           DATE,
  THP_PERIOD             DATE,
  THP_UNITS              NUMBER(12,2)           DEFAULT 0,
  THP_RATE               NUMBER(12,5)           DEFAULT 0,
  THP_AMOUNT             NUMBER(12,2)           DEFAULT 0,
  THP_PAYMENT_TYPE       VARCHAR2(10 BYTE),
  THP_COMMENT            VARCHAR2(3000 BYTE),
  THP_USER               VARCHAR2(100 BYTE),
  THP_DATE_TIME          DATE,
  THP_MEM_ID             VARCHAR2(15 BYTE),
  THP_TRAN_ID            VARCHAR2(15 BYTE),
  THP_POSTED_DATE        DATE,
  THP_POSTED_USER        VARCHAR2(100 BYTE),
  THP_CHEQUE             VARCHAR2(20 BYTE),
  THP_UNITS_EARNED       NUMBER(12,2)           DEFAULT 0,
  THP_RECD_AMT           NUMBER(12,2)           DEFAULT 0,
  THP_VARIANCE_AMT       NUMBER(12,2)           DEFAULT 0,
  THP_VAR_REASON         VARCHAR2(1000 BYTE),
  THP_CLIENT_ID          VARCHAR2(20 BYTE),
  THP_DEPOSIT_NUMBER     VARCHAR2(1000 BYTE),
  THP_AGREE_ID           VARCHAR2(20 BYTE),
  THP_EARNINGS           NUMBER(12,2)           DEFAULT 0,
  THP_VOL_UNITS          NUMBER(12,2)           DEFAULT 0,
  THP_HRS                NUMBER(12,2)           DEFAULT 0,
  THP_EE_UNITS           NUMBER(12,2)           DEFAULT 0,
  THP_ER_UNITS           NUMBER(12,2)           DEFAULT 0,
  THP_EE_ACCOUNT         VARCHAR2(10 BYTE),
  THP_ER_ACCOUNT         VARCHAR2(10 BYTE),
  THP_VOL_ACCOUNT        VARCHAR2(10 BYTE),
  THP_DEPOSIT_SLIP_DATE  DATE,
  THP_WRITE_OFF_AMT      NUMBER,
  THP_TRAN_LABEL         VARCHAR2(100 BYTE)
)
TABLESPACE CDATV5DATAFILE
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


