--
-- TRAN_HEADER_TEMP_FUNDS  (Table) 
--
CREATE TABLE OLIVER.TRAN_HEADER_TEMP_FUNDS
(
  THTF_EMPLOYER           VARCHAR2(100 BYTE)    NOT NULL,
  THTF_PLAN_ID            VARCHAR2(15 BYTE),
  THTF_START_DATE         DATE,
  THTF_END_DATE           DATE,
  THTF_PERIOD             DATE,
  THTF_UNITS              NUMBER(12,2)          DEFAULT 0,
  THTF_RATE               NUMBER(12,5)          DEFAULT 0,
  THTF_AMOUNT             NUMBER(12,2)          DEFAULT 0,
  THTF_PAYMENT_TYPE       VARCHAR2(10 BYTE),
  THTF_COMMENT            VARCHAR2(3000 BYTE),
  THTF_USER               VARCHAR2(100 BYTE),
  THTF_DATE_TIME          DATE,
  THTF_MEM_ID             VARCHAR2(15 BYTE),
  THTF_TRAN_ID            VARCHAR2(15 BYTE),
  THTF_POST               VARCHAR2(1 BYTE)      DEFAULT 'N',
  THTF_CHEQUE             VARCHAR2(20 BYTE),
  THTF_POSTED_DATE        DATE,
  THTF_EARNED             VARCHAR2(1 BYTE)      DEFAULT 'N',
  THTF_RECD_AMT           NUMBER(12,2)          DEFAULT 0,
  THTF_VARIANCE_AMT       NUMBER(12,2)          DEFAULT 0,
  THTF_VAR_REASON         VARCHAR2(1000 BYTE),
  THTF_CLIENT_ID          VARCHAR2(20 BYTE),
  THTF_DEPOSIT_NUMBER     VARCHAR2(1000 BYTE),
  THTF_AGREE_ID           VARCHAR2(100 BYTE),
  THTF_DEPOSIT_SLIP_DATE  DATE,
  THTF_WRITE_OFF_AMT      NUMBER,
  THTF_TRAN_LABEL         VARCHAR2(100 BYTE)
)
TABLESPACE CDATV5DATAFILE
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


