--
-- TRAN_HEADER_TEMP_PEN  (Table) 
--
CREATE TABLE OLIVER.TRAN_HEADER_TEMP_PEN
(
  THTP_EMPLOYER           VARCHAR2(100 BYTE)    NOT NULL,
  THTP_PLAN_ID            VARCHAR2(15 BYTE),
  THTP_START_DATE         DATE,
  THTP_END_DATE           DATE,
  THTP_PERIOD             DATE,
  THTP_UNITS              NUMBER(12,2)          DEFAULT 0,
  THTP_RATE               NUMBER(12,5)          DEFAULT 0,
  THTP_AMOUNT             NUMBER(12,2)          DEFAULT 0,
  THTP_PAYMENT_TYPE       VARCHAR2(10 BYTE),
  THTP_COMMENT            VARCHAR2(3000 BYTE),
  THTP_USER               VARCHAR2(100 BYTE),
  THTP_DATE_TIME          DATE,
  THTP_MEM_ID             VARCHAR2(15 BYTE),
  THTP_TRAN_ID            VARCHAR2(15 BYTE),
  THTP_POST               VARCHAR2(1 BYTE)      DEFAULT 'N',
  THTP_CHEQUE             VARCHAR2(20 BYTE),
  THTP_POSTED_DATE        DATE,
  THTP_EARNED             VARCHAR2(1 BYTE)      DEFAULT 'N',
  THTP_RECD_AMT           NUMBER(12,2)          DEFAULT 0,
  THTP_VARIANCE_AMT       NUMBER(12,2)          DEFAULT 0,
  THTP_VAR_REASON         VARCHAR2(1000 BYTE),
  THT_CLIENT_ID           VARCHAR2(20 BYTE),
  THTP_DEPOSIT_NUMBER     VARCHAR2(1000 BYTE),
  THTP_AGREE_ID           VARCHAR2(20 BYTE),
  THTP_EE_UNITS           NUMBER(12,2)          DEFAULT 0,
  THTP_ER_UNITS           NUMBER(12,2)          DEFAULT 0,
  THTP_EARNINGS           NUMBER(12,2)          DEFAULT 0,
  THTP_VOL_UNITS          NUMBER(12,2)          DEFAULT 0,
  THTP_HRS                NUMBER(12,2)          DEFAULT 0,
  THTP_EE_ACCOUNT         VARCHAR2(10 BYTE),
  THTP_ER_ACCOUNT         VARCHAR2(10 BYTE),
  THTP_VOL_ACCOUNT        VARCHAR2(10 BYTE),
  THTP_DEPOSIT_SLIP_DATE  DATE,
  THTP_WRITE_OFF_AMT      NUMBER,
  THTP_TRAN_LABEL         VARCHAR2(100 BYTE)
)
TABLESPACE CDATV5DATAFILE
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


