--
-- UNIFOR_TEMP_TABLE  (Table) 
--
CREATE TABLE OLIVER.UNIFOR_TEMP_TABLE
(
  MEMBER_EMPLOYER         VARCHAR2(150 BYTE),
  MEMBER_LAST_NAME        VARCHAR2(150 BYTE),
  MEMBERLASTNAME          VARCHAR2(150 BYTE),
  MEMBER_FIRST_NAME       VARCHAR2(150 BYTE),
  MEMBERFIRSTNAME         VARCHAR2(150 BYTE),
  MEMBER_MIDDLE_NAME      VARCHAR2(150 BYTE),
  MEMBERMIDDLENAME        VARCHAR2(150 BYTE),
  MEMBER_SIN              VARCHAR2(26 BYTE),
  MEMBER_ADDRESS1         VARCHAR2(128 BYTE),
  MEMBERADDRESS1          VARCHAR2(150 BYTE),
  MEMBER_ADDRESS2         VARCHAR2(26 BYTE),
  MEMBER_CITY             VARCHAR2(50 BYTE),
  MEMBERCITY              VARCHAR2(50 BYTE),
  MEMBER_PROV             VARCHAR2(26 BYTE),
  MEMBER_COUNTRY          VARCHAR2(26 BYTE),
  MEMBER_POSTAL_CODE      VARCHAR2(26 BYTE),
  MEMBER_HOME_PHONE       VARCHAR2(26 BYTE),
  MEMBER_WORK_PHONE       VARCHAR2(26 BYTE),
  MEMBER_CELL_PHONE       VARCHAR2(26 BYTE),
  MEMBER_GENDER           VARCHAR2(26 BYTE),
  MEMBER_DOB              VARCHAR2(26 BYTE),
  MEMBER_EMAIL            VARCHAR2(128 BYTE),
  MEMBERSTATUSCODE        VARCHAR2(26 BYTE),
  MEMBER_STATUS           VARCHAR2(26 BYTE),
  MEMBER_EFFECTIVE_DATE   DATE,
  PBC_ID                  NUMBER(11),
  MEMBER_UNION_LOCAL      VARCHAR2(26 BYTE),
  MEMBER_LOCAL_EFF_DATE   DATE,
  MEMBER_RECIPROCAL       VARCHAR2(26 BYTE),
  MEMBER_RECIPROCAL_DATE  VARCHAR2(26 BYTE),
  MEMBER_PLAN_CLASS       NUMBER(3),
  MEMBER_CATEGORY         VARCHAR2(26 BYTE),
  MEMBER_SMOKER           VARCHAR2(26 BYTE),
  MEMBER_EMPLOYMENT_TYPE  VARCHAR2(26 BYTE),
  SPOUSAL_SMOKER          VARCHAR2(26 BYTE),
  MEMBER_DEP_STATUS       VARCHAR2(26 BYTE),
  EMPLOYER_ID             VARCHAR2(20 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS ;


