--
-- CDAT  (Tablespace) 
--
CREATE TABLESPACE CDAT DATAFILE 
  'C:\APP\ADMINISTRATOR\VIRTUAL\ORADATA\CDAT\CDAT.DBF' SIZE 50M AUTOEXTEND ON NEXT 8K MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


