--
-- CDATV5DATAFILE  (Tablespace) 
--
CREATE TABLESPACE CDATV5DATAFILE DATAFILE 
  'C:\APP\ADMINISTRATOR\VIRTUAL\ORADATA\CDAT\OLIVER.DBF' SIZE 1010M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


