--
-- ICBA  (Tablespace) 
--
CREATE TABLESPACE ICBA DATAFILE 
  'C:\APP\ADMINISTRATOR\VIRTUAL\ORADATA\CDAT\ICBA.DBF' SIZE 20M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


