--
-- SUMA  (Tablespace) 
--
CREATE TABLESPACE SUMA DATAFILE 
  'C:\APP\ADMINISTRATOR\VIRTUAL\ORADATA\CDAT\SUMA.DBF' SIZE 210M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


