--
-- TL938  (Tablespace) 
--
CREATE TABLESPACE TL938 DATAFILE 
  'C:\APP\ADMINISTRATOR\VIRTUAL\ORADATA\CDAT\TL938.DBF' SIZE 30M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


