--
-- OLIVER  (User) 
--
CREATE USER OLIVER
  IDENTIFIED BY <password>
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 4 Roles for OLIVER 
  GRANT CONNECT TO OLIVER;
  GRANT DBA TO OLIVER;
  GRANT RESOURCE TO OLIVER;
  GRANT TC_ADMIN_ROLE TO OLIVER WITH ADMIN OPTION;
  ALTER USER OLIVER DEFAULT ROLE ALL;
  -- 4 System Privileges for OLIVER 
  GRANT ALTER SESSION TO OLIVER;
  GRANT CREATE ANY CONTEXT TO OLIVER;
  GRANT CREATE PUBLIC SYNONYM TO OLIVER;
  GRANT UNLIMITED TABLESPACE TO OLIVER;
  -- 1 Tablespace Quota for OLIVER 
  ALTER USER OLIVER QUOTA UNLIMITED ON CDATV5DATAFILE;


