--
-- AUDIT_UTILS  (Package) 
--
CREATE OR REPLACE PACKAGE OLIVER.AUDIT_UTILS AUTHID CURRENT_USER AS
    PROCEDURE CREATE_AUDIT_TABLES (
        TABLE_OWNER VARCHAR2
    );

    PROCEDURE CREATE_AUDIT_TRIGGERS (
        TABLE_OWNER    VARCHAR2,
        AUDIT_SCHEMA   VARCHAR2 DEFAULT 'OLIVER'
    );

    PROCEDURE POPULATE_APEX_LOG;

END AUDIT_UTILS;
/

