--
-- CONVERT_API  (Package) 
--
CREATE OR REPLACE PACKAGE OLIVER.CONVERT_API IS
    FUNCTION ENCRYPTS (
        P_INPUT VARCHAR2
    ) RETURN RAW;

    FUNCTION DECRYPTS (
        P_ENCRIPT_INPUT RAW
    ) RETURN VARCHAR2;

END CONVERT_API;
/

