--
-- INIT  (Package) 
--
CREATE OR REPLACE PACKAGE OLIVER.INIT AS
    PROCEDURE SETCLIENTID (
        CID VARCHAR2
    );

    FUNCTION BY_MEM_CLIENT (
        SCH VARCHAR2,
        TAB VARCHAR2
    ) RETURN VARCHAR2;

    FUNCTION BY_EMP_CLIENT (
        SCH VARCHAR2,
        TAB VARCHAR2
    ) RETURN VARCHAR2;

END INIT;
/

