--
-- PKG_INVOICING  (Package) 
--
CREATE OR REPLACE PACKAGE OLIVER.PKG_INVOICING AS
    FUNCTION GET_CLASS_NAME (
        P_PLAN_ID     IN TBL_BENEFITS_CLASS.BC_PLAN_ID%TYPE,
        P_CLIENT_ID   IN TBL_BENEFITS_CLASS.BC_CLIENT_ID%TYPE,
        P_CLASS_ID    IN TBL_BENEFITS_CLASS.BC_KEY%TYPE
    ) RETURN VARCHAR2;

END PKG_INVOICING;
/

