--
-- PKG_VALIDATION  (Package) 
--
CREATE OR REPLACE PACKAGE OLIVER.PKG_VALIDATION AS
    FUNCTION PHONE_REGEXP RETURN VARCHAR2;

    FUNCTION EMAIL_REGEXP RETURN VARCHAR2;

    FUNCTION POSTAL_CODE_REGEXP RETURN VARCHAR2;

    FUNCTION SIN_REGEXP RETURN VARCHAR2;

    FUNCTION PWD_FMT_REGEXP RETURN VARCHAR2;

    FUNCTION PWD_LEN_REGEXP RETURN VARCHAR2;

    FUNCTION DATE_FMT RETURN VARCHAR2;

    FUNCTION ALPHA_NUM_ONLY RETURN VARCHAR2;

    function is_sin_valid(p_client_id varchar2, p_plan_id varchar2, p_sin number) return varchar2;

END PKG_VALIDATION;

/

