--
-- PKG_CARRIER  (Package) 
--
CREATE OR REPLACE PACKAGE OLIVER.PKG_CARRIER AS
    FUNCTION CREATE_TRAN_ID RETURN VARCHAR2;

    PROCEDURE EXPORT_PAYMENT_DATA (
        P_PLAN_ID VARCHAR2,
        P_CARRIER_ID VARCHAR2
    );

END PKG_CARRIER;
/

