--
-- SAMPLE_DATA_PKG  (Package) 
--
CREATE OR REPLACE PACKAGE OLIVER.SAMPLE_DATA_PKG AS
    FUNCTION VARCHAR2_TO_BLOB (
        P_VARCHAR2_TAB IN DBMS_SQL.VARCHAR2_TABLE
    ) RETURN BLOB;

    PROCEDURE DELETE_DATA;

    PROCEDURE INSERT_DATA;

END SAMPLE_DATA_PKG;
/

